version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/apps/mobile'
    schedule:
      interval: 'monthly'
    groups:
      patch-dependencies:
        update-types:
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
