// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"
)

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, offsetx, offsety, type, zoom FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Offsetx,
		&i.Offsety,
		&i.Type,
		&i.Zoom,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :one
INSERT INTO assets (id, offsetx, offsety, type, zoom) VALUES ($1, $2, $3, $4, $5)
RETURNING id, offsetx, offsety, type, zoom
`

type InsertAssetParams struct {
	ID      string
	Offsetx float64
	Offsety float64
	Type    *int16
	Zoom    float64
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.Offsetx,
		arg.Offsety,
		arg.Type,
		arg.Zoom,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Offsetx,
		&i.Offsety,
		&i.Type,
		&i.Zoom,
	)
	return i, err
}
