// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
)

const activeMembershipID = `-- name: ActiveMembershipID :one
SELECT id FROM group_members
WHERE user_id = $1 AND group_id = $2 AND active
LIMIT 1
`

type ActiveMembershipIDParams struct {
	UserID  *string
	GroupID *string
}

func (q *Queries) ActiveMembershipID(ctx context.Context, arg ActiveMembershipIDParams) (string, error) {
	row := q.db.QueryRow(ctx, activeMembershipID, arg.UserID, arg.GroupID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const anyMembership = `-- name: AnyMembership :one
SELECT id, active FROM group_members
WHERE user_id = $1 AND group_id = $2
LIMIT 1
`

type AnyMembershipParams struct {
	UserID  *string
	GroupID *string
}

type AnyMembershipRow struct {
	ID     string
	Active bool
}

func (q *Queries) AnyMembership(ctx context.Context, arg AnyMembershipParams) (AnyMembershipRow, error) {
	row := q.db.QueryRow(ctx, anyMembership, arg.UserID, arg.GroupID)
	var i AnyMembershipRow
	err := row.Scan(&i.ID, &i.Active)
	return i, err
}

const authorizeRequest = `-- name: AuthorizeRequest :one
SELECT
    EXISTS (SELECT 1 FROM users u WHERE u.id = $1) AS user_exists,
    EXISTS (
        SELECT 1 FROM group_members gm
        WHERE gm.user_id = $1 AND gm.group_id = $2 AND gm.active
    ) AS is_member
`

type AuthorizeRequestParams struct {
	UserID  string
	GroupID *string
}

type AuthorizeRequestRow struct {
	UserExists bool
	IsMember   bool
}

// One round trip for the auth filter: does the user exist and is it an
// active member of the group in the path.
func (q *Queries) AuthorizeRequest(ctx context.Context, arg AuthorizeRequestParams) (AuthorizeRequestRow, error) {
	row := q.db.QueryRow(ctx, authorizeRequest, arg.UserID, arg.GroupID)
	var i AuthorizeRequestRow
	err := row.Scan(&i.UserExists, &i.IsMember)
	return i, err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, type, device_id, push_notification_token, user_id)
VALUES ($1, $2, $3, NULL, $4)
`

type CreateDeviceParams struct {
	ID       string
	Type     *int16
	DeviceID *string
	UserID   *string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.ID,
		arg.Type,
		arg.DeviceID,
		arg.UserID,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO group_members (id, active, group_id, user_id) VALUES ($1, true, $2, $3)
`

type CreateMembershipParams struct {
	ID      string
	GroupID *string
	UserID  *string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.ID, arg.GroupID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}

const setMembershipActive = `-- name: SetMembershipActive :exec
UPDATE group_members SET active = $2 WHERE id = $1
`

type SetMembershipActiveParams struct {
	ID     string
	Active bool
}

func (q *Queries) SetMembershipActive(ctx context.Context, arg SetMembershipActiveParams) error {
	_, err := q.db.Exec(ctx, setMembershipActive, arg.ID, arg.Active)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
