// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertMatchMoves implements pgx.CopyFromSource.
type iteratorForInsertMatchMoves struct {
	rows                 []InsertMatchMovesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertMatchMoves) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertMatchMoves) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Value,
		r.rows[0].TeamMemberID,
		r.rows[0].MoveID,
	}, nil
}

func (r iteratorForInsertMatchMoves) Err() error {
	return nil
}

func (q *Queries) InsertMatchMoves(ctx context.Context, arg []InsertMatchMovesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"match_moves"}, []string{"id", "value", "team_member_id", "move_id"}, &iteratorForInsertMatchMoves{rows: arg})
}

// iteratorForInsertPlayers implements pgx.CopyFromSource.
type iteratorForInsertPlayers struct {
	rows                 []InsertPlayersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPlayers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPlayers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ActiveThisSeason,
		r.rows[0].ProfileID,
		r.rows[0].SeasonID,
		r.rows[0].StatisticsID,
	}, nil
}

func (r iteratorForInsertPlayers) Err() error {
	return nil
}

func (q *Queries) InsertPlayers(ctx context.Context, arg []InsertPlayersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"players"}, []string{"id", "active_this_season", "profile_id", "season_id", "statistics_id"}, &iteratorForInsertPlayers{rows: arg})
}

// iteratorForInsertProfiles implements pgx.CopyFromSource.
type iteratorForInsertProfiles struct {
	rows                 []InsertProfilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertProfiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertProfiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].GroupID,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForInsertProfiles) Err() error {
	return nil
}

func (q *Queries) InsertProfiles(ctx context.Context, arg []InsertProfilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"profiles"}, []string{"id", "name", "group_id", "created_by"}, &iteratorForInsertProfiles{rows: arg})
}

// iteratorForInsertRuleMoves implements pgx.CopyFromSource.
type iteratorForInsertRuleMoves struct {
	rows                 []InsertRuleMovesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRuleMoves) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRuleMoves) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].FinishingMove,
		r.rows[0].Name,
		r.rows[0].PointsForScorer,
		r.rows[0].PointsForTeam,
		r.rows[0].SeasonID,
		r.rows[0].Cups,
	}, nil
}

func (r iteratorForInsertRuleMoves) Err() error {
	return nil
}

func (q *Queries) InsertRuleMoves(ctx context.Context, arg []InsertRuleMovesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rule_moves"}, []string{"id", "finishing_move", "name", "points_for_scorer", "points_for_team", "season_id", "cups"}, &iteratorForInsertRuleMoves{rows: arg})
}

// iteratorForInsertRules implements pgx.CopyFromSource.
type iteratorForInsertRules struct {
	rows                 []InsertRulesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRules) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRules) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Title,
		r.rows[0].Description,
		r.rows[0].SeasonID,
		r.rows[0].CreatedBy,
		r.rows[0].Position,
	}, nil
}

func (r iteratorForInsertRules) Err() error {
	return nil
}

func (q *Queries) InsertRules(ctx context.Context, arg []InsertRulesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rules"}, []string{"id", "title", "description", "season_id", "created_by", "position"}, &iteratorForInsertRules{rows: arg})
}

// iteratorForInsertStatistics implements pgx.CopyFromSource.
type iteratorForInsertStatistics struct {
	rows                 []InsertStatisticsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStatistics) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStatistics) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Points,
		r.rows[0].Matches,
		r.rows[0].Wins,
		r.rows[0].Moves,
		r.rows[0].TotalTeamSize,
		r.rows[0].AvgPointsPerMatch,
		r.rows[0].AvgTeamSize,
		r.rows[0].Elo,
	}, nil
}

func (r iteratorForInsertStatistics) Err() error {
	return nil
}

func (q *Queries) InsertStatistics(ctx context.Context, arg []InsertStatisticsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"statistics"}, []string{"id", "points", "matches", "wins", "moves", "total_team_size", "avg_points_per_match", "avg_team_size", "elo"}, &iteratorForInsertStatistics{rows: arg})
}

// iteratorForInsertTeamMembers implements pgx.CopyFromSource.
type iteratorForInsertTeamMembers struct {
	rows                 []InsertTeamMembersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTeamMembers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTeamMembers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TeamID,
		r.rows[0].PlayerID,
	}, nil
}

func (r iteratorForInsertTeamMembers) Err() error {
	return nil
}

func (q *Queries) InsertTeamMembers(ctx context.Context, arg []InsertTeamMembersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"team_members"}, []string{"id", "team_id", "player_id"}, &iteratorForInsertTeamMembers{rows: arg})
}

// iteratorForInsertTeams implements pgx.CopyFromSource.
type iteratorForInsertTeams struct {
	rows                 []InsertTeamsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTeams) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTeams) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MatchID,
		r.rows[0].AssetIDPhoto,
	}, nil
}

func (r iteratorForInsertTeams) Err() error {
	return nil
}

func (q *Queries) InsertTeams(ctx context.Context, arg []InsertTeamsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teams"}, []string{"id", "match_id", "asset_id_photo"}, &iteratorForInsertTeams{rows: arg})
}
