// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: live_matches.sql

package db

import (
	"context"
	"time"
)

const endLiveMatch = `-- name: EndLiveMatch :exec
UPDATE live_matches SET status = $2, ended_at = $3, result_match_id = $4 WHERE id = $1
`

type EndLiveMatchParams struct {
	ID            string
	Status        string
	EndedAt       *time.Time
	ResultMatchID *string
}

func (q *Queries) EndLiveMatch(ctx context.Context, arg EndLiveMatchParams) error {
	_, err := q.db.Exec(ctx, endLiveMatch,
		arg.ID,
		arg.Status,
		arg.EndedAt,
		arg.ResultMatchID,
	)
	return err
}

const finishedLiveMatchesBySeason = `-- name: FinishedLiveMatchesBySeason :many
SELECT lm.id, lm.group_id, lm.season_id, lm.created_by, lm.status, lm.started_at, lm.last_activity_at, lm.ended_at, lm.last_seq, lm.result_match_id, lm.display, lm.display_seq, lm.activity_channel, lm.activity_ended, lm.tournament_id, lm.tournament_stage, gm.user_id AS created_by_user_id
FROM live_matches lm
JOIN group_members gm ON gm.id = lm.created_by
JOIN matches m ON m.id = lm.result_match_id
WHERE lm.group_id = $1 AND lm.season_id = $2 AND lm.status = 'FINISHED'
ORDER BY lm.started_at, lm.id
`

type FinishedLiveMatchesBySeasonParams struct {
	GroupID  string
	SeasonID string
}

type FinishedLiveMatchesBySeasonRow struct {
	LiveMatch       LiveMatch
	CreatedByUserID *string
}

// the season's live matches that became a match, oldest first: the Elo
// simulator replays their ops
func (q *Queries) FinishedLiveMatchesBySeason(ctx context.Context, arg FinishedLiveMatchesBySeasonParams) ([]FinishedLiveMatchesBySeasonRow, error) {
	rows, err := q.db.Query(ctx, finishedLiveMatchesBySeason, arg.GroupID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinishedLiveMatchesBySeasonRow
	for rows.Next() {
		var i FinishedLiveMatchesBySeasonRow
		if err := rows.Scan(
			&i.LiveMatch.ID,
			&i.LiveMatch.GroupID,
			&i.LiveMatch.SeasonID,
			&i.LiveMatch.CreatedBy,
			&i.LiveMatch.Status,
			&i.LiveMatch.StartedAt,
			&i.LiveMatch.LastActivityAt,
			&i.LiveMatch.EndedAt,
			&i.LiveMatch.LastSeq,
			&i.LiveMatch.ResultMatchID,
			&i.LiveMatch.Display,
			&i.LiveMatch.DisplaySeq,
			&i.LiveMatch.ActivityChannel,
			&i.LiveMatch.ActivityEnded,
			&i.LiveMatch.TournamentID,
			&i.LiveMatch.TournamentStage,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveMatch = `-- name: GetLiveMatch :one
SELECT lm.id, lm.group_id, lm.season_id, lm.created_by, lm.status, lm.started_at, lm.last_activity_at, lm.ended_at, lm.last_seq, lm.result_match_id, lm.display, lm.display_seq, lm.activity_channel, lm.activity_ended, lm.tournament_id, lm.tournament_stage, gm.user_id AS created_by_user_id
FROM live_matches lm
JOIN group_members gm ON gm.id = lm.created_by
WHERE lm.id = $1
`

type GetLiveMatchRow struct {
	LiveMatch       LiveMatch
	CreatedByUserID *string
}

func (q *Queries) GetLiveMatch(ctx context.Context, id string) (GetLiveMatchRow, error) {
	row := q.db.QueryRow(ctx, getLiveMatch, id)
	var i GetLiveMatchRow
	err := row.Scan(
		&i.LiveMatch.ID,
		&i.LiveMatch.GroupID,
		&i.LiveMatch.SeasonID,
		&i.LiveMatch.CreatedBy,
		&i.LiveMatch.Status,
		&i.LiveMatch.StartedAt,
		&i.LiveMatch.LastActivityAt,
		&i.LiveMatch.EndedAt,
		&i.LiveMatch.LastSeq,
		&i.LiveMatch.ResultMatchID,
		&i.LiveMatch.Display,
		&i.LiveMatch.DisplaySeq,
		&i.LiveMatch.ActivityChannel,
		&i.LiveMatch.ActivityEnded,
		&i.LiveMatch.TournamentID,
		&i.LiveMatch.TournamentStage,
		&i.CreatedByUserID,
	)
	return i, err
}

const inProgressLiveMatchesByGroup = `-- name: InProgressLiveMatchesByGroup :many
SELECT lm.id, lm.group_id, lm.season_id, lm.created_by, lm.status, lm.started_at, lm.last_activity_at, lm.ended_at, lm.last_seq, lm.result_match_id, lm.display, lm.display_seq, lm.activity_channel, lm.activity_ended, lm.tournament_id, lm.tournament_stage, gm.user_id AS created_by_user_id
FROM live_matches lm
JOIN group_members gm ON gm.id = lm.created_by
WHERE lm.group_id = $1 AND lm.status = 'IN_PROGRESS'
ORDER BY lm.last_activity_at DESC, lm.started_at DESC, lm.id
`

type InProgressLiveMatchesByGroupRow struct {
	LiveMatch       LiveMatch
	CreatedByUserID *string
}

func (q *Queries) InProgressLiveMatchesByGroup(ctx context.Context, groupID string) ([]InProgressLiveMatchesByGroupRow, error) {
	rows, err := q.db.Query(ctx, inProgressLiveMatchesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InProgressLiveMatchesByGroupRow
	for rows.Next() {
		var i InProgressLiveMatchesByGroupRow
		if err := rows.Scan(
			&i.LiveMatch.ID,
			&i.LiveMatch.GroupID,
			&i.LiveMatch.SeasonID,
			&i.LiveMatch.CreatedBy,
			&i.LiveMatch.Status,
			&i.LiveMatch.StartedAt,
			&i.LiveMatch.LastActivityAt,
			&i.LiveMatch.EndedAt,
			&i.LiveMatch.LastSeq,
			&i.LiveMatch.ResultMatchID,
			&i.LiveMatch.Display,
			&i.LiveMatch.DisplaySeq,
			&i.LiveMatch.ActivityChannel,
			&i.LiveMatch.ActivityEnded,
			&i.LiveMatch.TournamentID,
			&i.LiveMatch.TournamentStage,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLiveMatch = `-- name: InsertLiveMatch :execrows
INSERT INTO live_matches (id, group_id, season_id, created_by, status, started_at, last_activity_at, last_seq)
VALUES ($1, $2, $3, $4, 'IN_PROGRESS', $5, $5, 0)
ON CONFLICT (id) DO NOTHING
`

type InsertLiveMatchParams struct {
	ID        string
	GroupID   string
	SeasonID  string
	CreatedBy string
	StartedAt time.Time
}

func (q *Queries) InsertLiveMatch(ctx context.Context, arg InsertLiveMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLiveMatch,
		arg.ID,
		arg.GroupID,
		arg.SeasonID,
		arg.CreatedBy,
		arg.StartedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLiveMatchOp = `-- name: InsertLiveMatchOp :execrows
INSERT INTO live_match_ops (id, live_match_id, seq, created_at, created_by, type, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type InsertLiveMatchOpParams struct {
	ID          string
	LiveMatchID string
	Seq         int64
	CreatedAt   time.Time
	CreatedBy   string
	Type        string
	Payload     string
}

func (q *Queries) InsertLiveMatchOp(ctx context.Context, arg InsertLiveMatchOpParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLiveMatchOp,
		arg.ID,
		arg.LiveMatchID,
		arg.Seq,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Type,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liveMatchOpsByIDs = `-- name: LiveMatchOpsByIDs :many
SELECT id, live_match_id, seq, created_at, created_by, type, payload FROM live_match_ops WHERE id = ANY ($1::text[])
`

func (q *Queries) LiveMatchOpsByIDs(ctx context.Context, ids []string) ([]LiveMatchOp, error) {
	rows, err := q.db.Query(ctx, liveMatchOpsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveMatchOp
	for rows.Next() {
		var i LiveMatchOp
		if err := rows.Scan(
			&i.ID,
			&i.LiveMatchID,
			&i.Seq,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Type,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveMatchOpsByLiveMatchIDs = `-- name: LiveMatchOpsByLiveMatchIDs :many
SELECT id, live_match_id, seq, created_at, created_by, type, payload FROM live_match_ops WHERE live_match_id = ANY ($1::text[]) ORDER BY live_match_id, seq
`

func (q *Queries) LiveMatchOpsByLiveMatchIDs(ctx context.Context, liveMatchIds []string) ([]LiveMatchOp, error) {
	rows, err := q.db.Query(ctx, liveMatchOpsByLiveMatchIDs, liveMatchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveMatchOp
	for rows.Next() {
		var i LiveMatchOp
		if err := rows.Scan(
			&i.ID,
			&i.LiveMatchID,
			&i.Seq,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Type,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveMatch = `-- name: LockLiveMatch :one
SELECT lm.id, lm.group_id, lm.season_id, lm.created_by, lm.status, lm.started_at, lm.last_activity_at, lm.ended_at, lm.last_seq, lm.result_match_id, lm.display, lm.display_seq, lm.activity_channel, lm.activity_ended, lm.tournament_id, lm.tournament_stage, gm.user_id AS created_by_user_id
FROM live_matches lm
JOIN group_members gm ON gm.id = lm.created_by
WHERE lm.id = $1 AND lm.group_id = $2
FOR UPDATE OF lm
`

type LockLiveMatchParams struct {
	ID      string
	GroupID string
}

type LockLiveMatchRow struct {
	LiveMatch       LiveMatch
	CreatedByUserID *string
}

// Every write to a live match runs in a transaction that first takes this lock,
// so seq is assigned one request at a time.
func (q *Queries) LockLiveMatch(ctx context.Context, arg LockLiveMatchParams) (LockLiveMatchRow, error) {
	row := q.db.QueryRow(ctx, lockLiveMatch, arg.ID, arg.GroupID)
	var i LockLiveMatchRow
	err := row.Scan(
		&i.LiveMatch.ID,
		&i.LiveMatch.GroupID,
		&i.LiveMatch.SeasonID,
		&i.LiveMatch.CreatedBy,
		&i.LiveMatch.Status,
		&i.LiveMatch.StartedAt,
		&i.LiveMatch.LastActivityAt,
		&i.LiveMatch.EndedAt,
		&i.LiveMatch.LastSeq,
		&i.LiveMatch.ResultMatchID,
		&i.LiveMatch.Display,
		&i.LiveMatch.DisplaySeq,
		&i.LiveMatch.ActivityChannel,
		&i.LiveMatch.ActivityEnded,
		&i.LiveMatch.TournamentID,
		&i.LiveMatch.TournamentStage,
		&i.CreatedByUserID,
	)
	return i, err
}

const setLiveMatchProgress = `-- name: SetLiveMatchProgress :exec
UPDATE live_matches SET last_seq = $2, last_activity_at = $3 WHERE id = $1
`

type SetLiveMatchProgressParams struct {
	ID             string
	LastSeq        int64
	LastActivityAt time.Time
}

func (q *Queries) SetLiveMatchProgress(ctx context.Context, arg SetLiveMatchProgressParams) error {
	_, err := q.db.Exec(ctx, setLiveMatchProgress, arg.ID, arg.LastSeq, arg.LastActivityAt)
	return err
}

const staleLiveMatches = `-- name: StaleLiveMatches :many
SELECT id, group_id FROM live_matches WHERE status = 'IN_PROGRESS' AND last_activity_at < $1
`

type StaleLiveMatchesRow struct {
	ID      string
	GroupID string
}

// Candidates for expiry. The caller locks and re-reads each one before it decides.
func (q *Queries) StaleLiveMatches(ctx context.Context, lastActivityAt time.Time) ([]StaleLiveMatchesRow, error) {
	rows, err := q.db.Query(ctx, staleLiveMatches, lastActivityAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaleLiveMatchesRow
	for rows.Next() {
		var i StaleLiveMatchesRow
		if err := rows.Scan(&i.ID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
