// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"
	"time"
)

const countTeams = `-- name: CountTeams :one
SELECT count(id) FROM teams WHERE id = ANY ($1::text[])
`

func (q *Queries) CountTeams(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMatch, id)
	return err
}

const deleteMatchMovesOfMatch = `-- name: DeleteMatchMovesOfMatch :exec
DELETE FROM match_moves mm
USING team_members tm, teams t
WHERE mm.team_member_id = tm.id AND tm.team_id = t.id AND t.match_id = $1
`

func (q *Queries) DeleteMatchMovesOfMatch(ctx context.Context, matchID *string) error {
	_, err := q.db.Exec(ctx, deleteMatchMovesOfMatch, matchID)
	return err
}

const deleteTeamMembersOfMatch = `-- name: DeleteTeamMembersOfMatch :exec
DELETE FROM team_members tm
USING teams t
WHERE tm.team_id = t.id AND t.match_id = $1
`

func (q *Queries) DeleteTeamMembersOfMatch(ctx context.Context, matchID *string) error {
	_, err := q.db.Exec(ctx, deleteTeamMembersOfMatch, matchID)
	return err
}

const deleteTeamsOfMatch = `-- name: DeleteTeamsOfMatch :exec
DELETE FROM teams WHERE match_id = $1
`

func (q *Queries) DeleteTeamsOfMatch(ctx context.Context, matchID *string) error {
	_, err := q.db.Exec(ctx, deleteTeamsOfMatch, matchID)
	return err
}

const getMatch = `-- name: GetMatch :one
SELECT id, date, season_id, created_by, tournament_id, tournament_stage FROM matches WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.SeasonID,
		&i.CreatedBy,
		&i.TournamentID,
		&i.TournamentStage,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, match_id, asset_id_photo FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.MatchID, &i.AssetIDPhoto)
	return i, err
}

const insertMatch = `-- name: InsertMatch :exec

INSERT INTO matches (id, date, season_id, created_by) VALUES ($1, $2, $3, $4)
`

type InsertMatchParams struct {
	ID        string
	Date      *time.Time
	SeasonID  *string
	CreatedBy *string
}

// Lists are ordered by ctid, the physical row order. The Java backend sent
// no ORDER BY, so its clients got rows in that order (e.g. the first team of
// a match is "blue"); ordering explicitly keeps it stable across query plans.
func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) error {
	_, err := q.db.Exec(ctx, insertMatch,
		arg.ID,
		arg.Date,
		arg.SeasonID,
		arg.CreatedBy,
	)
	return err
}

type InsertMatchMovesParams struct {
	ID           string
	Value        int32
	TeamMemberID *string
	MoveID       *string
}

type InsertTeamMembersParams struct {
	ID       string
	TeamID   *string
	PlayerID *string
}

type InsertTeamsParams struct {
	ID           string
	MatchID      *string
	AssetIDPhoto *string
}

const matchCountsBySeason = `-- name: MatchCountsBySeason :many
SELECT m.season_id, count(*) AS matches FROM matches m
JOIN seasons s ON s.id = m.season_id
WHERE s.group_id = $1
GROUP BY m.season_id
`

type MatchCountsBySeasonRow struct {
	SeasonID *string
	Matches  int64
}

func (q *Queries) MatchCountsBySeason(ctx context.Context, groupID *string) ([]MatchCountsBySeasonRow, error) {
	rows, err := q.db.Query(ctx, matchCountsBySeason, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchCountsBySeasonRow
	for rows.Next() {
		var i MatchCountsBySeasonRow
		if err := rows.Scan(&i.SeasonID, &i.Matches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchExistsInSeason = `-- name: MatchExistsInSeason :one
SELECT EXISTS (SELECT 1 FROM matches WHERE id = $1 AND season_id = $2)
`

type MatchExistsInSeasonParams struct {
	ID       string
	SeasonID *string
}

func (q *Queries) MatchExistsInSeason(ctx context.Context, arg MatchExistsInSeasonParams) (bool, error) {
	row := q.db.QueryRow(ctx, matchExistsInSeason, arg.ID, arg.SeasonID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const matchMovesByTeamMemberIDs = `-- name: MatchMovesByTeamMemberIDs :many
SELECT id, value, move_id, team_member_id FROM match_moves WHERE team_member_id = ANY ($1::text[]) ORDER BY ctid
`

func (q *Queries) MatchMovesByTeamMemberIDs(ctx context.Context, teamMemberIds []string) ([]MatchMove, error) {
	rows, err := q.db.Query(ctx, matchMovesByTeamMemberIDs, teamMemberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchMove
	for rows.Next() {
		var i MatchMove
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.MoveID,
			&i.TeamMemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchesByGroup = `-- name: MatchesByGroup :many
SELECT id, date, season_id, created_by, tournament_id, tournament_stage FROM matches WHERE season_id IN (SELECT id FROM seasons WHERE group_id = $1) ORDER BY ctid
`

// Every season's matches of a group, for boards that replay all seasons.
func (q *Queries) MatchesByGroup(ctx context.Context, groupID *string) ([]Match, error) {
	rows, err := q.db.Query(ctx, matchesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SeasonID,
			&i.CreatedBy,
			&i.TournamentID,
			&i.TournamentStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchesBySeason = `-- name: MatchesBySeason :many
SELECT id, date, season_id, created_by, tournament_id, tournament_stage FROM matches WHERE season_id = $1 ORDER BY ctid
`

func (q *Queries) MatchesBySeason(ctx context.Context, seasonID *string) ([]Match, error) {
	rows, err := q.db.Query(ctx, matchesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SeasonID,
			&i.CreatedBy,
			&i.TournamentID,
			&i.TournamentStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchesBySeasonSince = `-- name: MatchesBySeasonSince :many
SELECT id, date, season_id, created_by, tournament_id, tournament_stage FROM matches WHERE season_id = $1 AND date >= $2 ORDER BY ctid
`

type MatchesBySeasonSinceParams struct {
	SeasonID *string
	Date     *time.Time
}

func (q *Queries) MatchesBySeasonSince(ctx context.Context, arg MatchesBySeasonSinceParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, matchesBySeasonSince, arg.SeasonID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SeasonID,
			&i.CreatedBy,
			&i.TournamentID,
			&i.TournamentStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const photoAssetIDsOfMatch = `-- name: PhotoAssetIDsOfMatch :many
SELECT asset_id_photo::text FROM teams WHERE match_id = $1 AND asset_id_photo IS NOT NULL
`

func (q *Queries) PhotoAssetIDsOfMatch(ctx context.Context, matchID *string) ([]string, error) {
	rows, err := q.db.Query(ctx, photoAssetIDsOfMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id_photo string
		if err := rows.Scan(&asset_id_photo); err != nil {
			return nil, err
		}
		items = append(items, asset_id_photo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamPhoto = `-- name: SetTeamPhoto :one
UPDATE teams SET asset_id_photo = $2 WHERE id = $1
RETURNING id, match_id, asset_id_photo
`

type SetTeamPhotoParams struct {
	ID           string
	AssetIDPhoto *string
}

func (q *Queries) SetTeamPhoto(ctx context.Context, arg SetTeamPhotoParams) (Team, error) {
	row := q.db.QueryRow(ctx, setTeamPhoto, arg.ID, arg.AssetIDPhoto)
	var i Team
	err := row.Scan(&i.ID, &i.MatchID, &i.AssetIDPhoto)
	return i, err
}

const teamExistsInMatch = `-- name: TeamExistsInMatch :one
SELECT EXISTS (SELECT 1 FROM teams WHERE id = $1 AND match_id = $2)
`

type TeamExistsInMatchParams struct {
	ID      string
	MatchID *string
}

func (q *Queries) TeamExistsInMatch(ctx context.Context, arg TeamExistsInMatchParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamExistsInMatch, arg.ID, arg.MatchID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const teamMembersByTeamIDs = `-- name: TeamMembersByTeamIDs :many
SELECT id, player_id, team_id FROM team_members WHERE team_id = ANY ($1::text[]) ORDER BY ctid
`

func (q *Queries) TeamMembersByTeamIDs(ctx context.Context, teamIds []string) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, teamMembersByTeamIDs, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(&i.ID, &i.PlayerID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamsByMatchIDs = `-- name: TeamsByMatchIDs :many
SELECT id, match_id, asset_id_photo FROM teams WHERE match_id = ANY ($1::text[]) ORDER BY ctid
`

func (q *Queries) TeamsByMatchIDs(ctx context.Context, matchIds []string) ([]Team, error) {
	rows, err := q.db.Query(ctx, teamsByMatchIDs, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.MatchID, &i.AssetIDPhoto); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
