// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"time"
)

const existingPlayerIDs = `-- name: ExistingPlayerIDs :many
SELECT id FROM players WHERE id = ANY ($1::text[])
`

func (q *Queries) ExistingPlayerIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingPlayerIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const existingPlayersInSeason = `-- name: ExistingPlayersInSeason :one
SELECT count(*) FROM players WHERE id = ANY ($2::text[]) AND season_id = $1
`

type ExistingPlayersInSeasonParams struct {
	SeasonID *string
	Ids      []string
}

func (q *Queries) ExistingPlayersInSeason(ctx context.Context, arg ExistingPlayersInSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, existingPlayersInSeason, arg.SeasonID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlayerWithSeason = `-- name: GetPlayerWithSeason :one
SELECT p.id, p.active_this_season, p.profile_id, p.season_id, p.statistics_id, s.group_id AS season_group_id, s.end_date AS season_end_date
FROM players p
LEFT JOIN seasons s ON s.id = p.season_id
WHERE p.id = $1
`

type GetPlayerWithSeasonRow struct {
	Player        Player
	SeasonGroupID *string
	SeasonEndDate *time.Time
}

func (q *Queries) GetPlayerWithSeason(ctx context.Context, id string) (GetPlayerWithSeasonRow, error) {
	row := q.db.QueryRow(ctx, getPlayerWithSeason, id)
	var i GetPlayerWithSeasonRow
	err := row.Scan(
		&i.Player.ID,
		&i.Player.ActiveThisSeason,
		&i.Player.ProfileID,
		&i.Player.SeasonID,
		&i.Player.StatisticsID,
		&i.SeasonGroupID,
		&i.SeasonEndDate,
	)
	return i, err
}

type InsertPlayersParams struct {
	ID               string
	ActiveThisSeason bool
	ProfileID        *string
	SeasonID         *string
	StatisticsID     *string
}

type InsertStatisticsParams struct {
	ID                string
	Points            int64
	Matches           int64
	Wins              *int64
	Moves             int64
	TotalTeamSize     int64
	AvgPointsPerMatch float64
	AvgTeamSize       float64
	Elo               float64
}

const latestPlayerOfProfile = `-- name: LatestPlayerOfProfile :one
SELECT
    p.id, p.season_id,
    st.points, st.matches, st.wins, st.moves, st.total_team_size,
    st.avg_points_per_match, st.avg_team_size, st.elo
FROM players p
JOIN seasons s ON s.id = p.season_id
LEFT JOIN statistics st ON st.id = p.statistics_id
WHERE p.profile_id = $1
ORDER BY s.start_date DESC
LIMIT 1
`

type LatestPlayerOfProfileRow struct {
	ID                string
	SeasonID          *string
	Points            *int64
	Matches           *int64
	Wins              *int64
	Moves             *int64
	TotalTeamSize     *int64
	AvgPointsPerMatch *float64
	AvgTeamSize       *float64
	Elo               *float64
}

func (q *Queries) LatestPlayerOfProfile(ctx context.Context, profileID *string) (LatestPlayerOfProfileRow, error) {
	row := q.db.QueryRow(ctx, latestPlayerOfProfile, profileID)
	var i LatestPlayerOfProfileRow
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Points,
		&i.Matches,
		&i.Wins,
		&i.Moves,
		&i.TotalTeamSize,
		&i.AvgPointsPerMatch,
		&i.AvgTeamSize,
		&i.Elo,
	)
	return i, err
}

const playerIDByProfileAndSeason = `-- name: PlayerIDByProfileAndSeason :one
SELECT id FROM players WHERE profile_id = $1 AND season_id = $2 LIMIT 1
`

type PlayerIDByProfileAndSeasonParams struct {
	ProfileID *string
	SeasonID  *string
}

func (q *Queries) PlayerIDByProfileAndSeason(ctx context.Context, arg PlayerIDByProfileAndSeasonParams) (string, error) {
	row := q.db.QueryRow(ctx, playerIDByProfileAndSeason, arg.ProfileID, arg.SeasonID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const playerIDsInSeason = `-- name: PlayerIDsInSeason :many
SELECT id FROM players
WHERE season_id = $1 AND (active_this_season OR $2::boolean)
ORDER BY ctid
`

type PlayerIDsInSeasonParams struct {
	SeasonID        *string
	IncludeInactive bool
}

func (q *Queries) PlayerIDsInSeason(ctx context.Context, arg PlayerIDsInSeasonParams) ([]string, error) {
	rows, err := q.db.Query(ctx, playerIDsInSeason, arg.SeasonID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playersInSeason = `-- name: PlayersInSeason :many
SELECT id, active_this_season, profile_id, season_id, statistics_id FROM players
WHERE season_id = $1 AND (active_this_season OR $2::boolean)
ORDER BY ctid
`

type PlayersInSeasonParams struct {
	SeasonID        *string
	IncludeInactive bool
}

func (q *Queries) PlayersInSeason(ctx context.Context, arg PlayersInSeasonParams) ([]Player, error) {
	rows, err := q.db.Query(ctx, playersInSeason, arg.SeasonID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.ActiveThisSeason,
			&i.ProfileID,
			&i.SeasonID,
			&i.StatisticsID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playersWithStatsInGroup = `-- name: PlayersWithStatsInGroup :many
SELECT
    p.id, p.profile_id, p.active_this_season,
    st.points, st.matches, st.wins, st.moves, st.total_team_size,
    st.avg_points_per_match, st.avg_team_size, st.elo,
    s.id AS season_id, s.name AS season_name, s.start_date AS season_start_date, s.end_date AS season_end_date,
    ss.min_matches_to_qualify, ss.min_team_size, ss.max_team_size,
    ss.ranking_algorithm, ss.daily_leaderboard,
    ss.elo_k, ss.elo_kr, ss.elo_ring_weight, ss.elo_swing, ss.elo_spread,
    COALESCE(to_char(ss.wake_time, 'HH24:MI:SS'), '00:00')::text AS wake_time
FROM players p
JOIN statistics st ON st.id = p.statistics_id
JOIN seasons s ON s.id = p.season_id
LEFT JOIN season_settings ss ON ss.id = s.season_settings_id
WHERE s.group_id = $1
ORDER BY p.ctid
`

type PlayersWithStatsInGroupRow struct {
	ID                  string
	ProfileID           *string
	ActiveThisSeason    bool
	Points              int64
	Matches             int64
	Wins                *int64
	Moves               int64
	TotalTeamSize       int64
	AvgPointsPerMatch   float64
	AvgTeamSize         float64
	Elo                 float64
	SeasonID            string
	SeasonName          *string
	SeasonStartDate     *time.Time
	SeasonEndDate       *time.Time
	MinMatchesToQualify *int32
	MinTeamSize         *int32
	MaxTeamSize         *int32
	RankingAlgorithm    *int16
	DailyLeaderboard    *int16
	EloK                *float64
	EloKr               *float64
	EloRingWeight       *float64
	EloSwing            *float64
	EloSpread           *float64
	WakeTime            string
}

// PlayersWithStatsInSeason for every season of a group.
func (q *Queries) PlayersWithStatsInGroup(ctx context.Context, groupID *string) ([]PlayersWithStatsInGroupRow, error) {
	rows, err := q.db.Query(ctx, playersWithStatsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayersWithStatsInGroupRow
	for rows.Next() {
		var i PlayersWithStatsInGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ActiveThisSeason,
			&i.Points,
			&i.Matches,
			&i.Wins,
			&i.Moves,
			&i.TotalTeamSize,
			&i.AvgPointsPerMatch,
			&i.AvgTeamSize,
			&i.Elo,
			&i.SeasonID,
			&i.SeasonName,
			&i.SeasonStartDate,
			&i.SeasonEndDate,
			&i.MinMatchesToQualify,
			&i.MinTeamSize,
			&i.MaxTeamSize,
			&i.RankingAlgorithm,
			&i.DailyLeaderboard,
			&i.EloK,
			&i.EloKr,
			&i.EloRingWeight,
			&i.EloSwing,
			&i.EloSpread,
			&i.WakeTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playersWithStatsInSeason = `-- name: PlayersWithStatsInSeason :many
SELECT
    p.id, p.profile_id, p.active_this_season,
    st.points, st.matches, st.wins, st.moves, st.total_team_size,
    st.avg_points_per_match, st.avg_team_size, st.elo,
    s.id AS season_id, s.name AS season_name, s.start_date AS season_start_date, s.end_date AS season_end_date,
    ss.min_matches_to_qualify, ss.min_team_size, ss.max_team_size,
    ss.ranking_algorithm, ss.daily_leaderboard,
    ss.elo_k, ss.elo_kr, ss.elo_ring_weight, ss.elo_swing, ss.elo_spread,
    -- Java's DTO renders a missing wake time as its default "00:00"
    COALESCE(to_char(ss.wake_time, 'HH24:MI:SS'), '00:00')::text AS wake_time
FROM players p
JOIN statistics st ON st.id = p.statistics_id
JOIN seasons s ON s.id = p.season_id
LEFT JOIN season_settings ss ON ss.id = s.season_settings_id
WHERE p.season_id = $1
  AND ($2::text[] IS NULL OR p.id = ANY ($2::text[]))
ORDER BY p.ctid
`

type PlayersWithStatsInSeasonParams struct {
	SeasonID  *string
	PlayerIds []string
}

type PlayersWithStatsInSeasonRow struct {
	ID                  string
	ProfileID           *string
	ActiveThisSeason    bool
	Points              int64
	Matches             int64
	Wins                *int64
	Moves               int64
	TotalTeamSize       int64
	AvgPointsPerMatch   float64
	AvgTeamSize         float64
	Elo                 float64
	SeasonID            string
	SeasonName          *string
	SeasonStartDate     *time.Time
	SeasonEndDate       *time.Time
	MinMatchesToQualify *int32
	MinTeamSize         *int32
	MaxTeamSize         *int32
	RankingAlgorithm    *int16
	DailyLeaderboard    *int16
	EloK                *float64
	EloKr               *float64
	EloRingWeight       *float64
	EloSwing            *float64
	EloSpread           *float64
	WakeTime            string
}

func (q *Queries) PlayersWithStatsInSeason(ctx context.Context, arg PlayersWithStatsInSeasonParams) ([]PlayersWithStatsInSeasonRow, error) {
	rows, err := q.db.Query(ctx, playersWithStatsInSeason, arg.SeasonID, arg.PlayerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayersWithStatsInSeasonRow
	for rows.Next() {
		var i PlayersWithStatsInSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ActiveThisSeason,
			&i.Points,
			&i.Matches,
			&i.Wins,
			&i.Moves,
			&i.TotalTeamSize,
			&i.AvgPointsPerMatch,
			&i.AvgTeamSize,
			&i.Elo,
			&i.SeasonID,
			&i.SeasonName,
			&i.SeasonStartDate,
			&i.SeasonEndDate,
			&i.MinMatchesToQualify,
			&i.MinTeamSize,
			&i.MaxTeamSize,
			&i.RankingAlgorithm,
			&i.DailyLeaderboard,
			&i.EloK,
			&i.EloKr,
			&i.EloRingWeight,
			&i.EloSwing,
			&i.EloSpread,
			&i.WakeTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileIDsOfPlayers = `-- name: ProfileIDsOfPlayers :many
SELECT id, profile_id FROM players WHERE id = ANY ($1::text[])
`

type ProfileIDsOfPlayersRow struct {
	ID        string
	ProfileID *string
}

func (q *Queries) ProfileIDsOfPlayers(ctx context.Context, ids []string) ([]ProfileIDsOfPlayersRow, error) {
	rows, err := q.db.Query(ctx, profileIDsOfPlayers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileIDsOfPlayersRow
	for rows.Next() {
		var i ProfileIDsOfPlayersRow
		if err := rows.Scan(&i.ID, &i.ProfileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerActive = `-- name: SetPlayerActive :exec
UPDATE players SET active_this_season = $2 WHERE id = $1
`

type SetPlayerActiveParams struct {
	ID               string
	ActiveThisSeason bool
}

func (q *Queries) SetPlayerActive(ctx context.Context, arg SetPlayerActiveParams) error {
	_, err := q.db.Exec(ctx, setPlayerActive, arg.ID, arg.ActiveThisSeason)
	return err
}
