// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: premium.sql

package db

import (
	"context"
	"time"
)

const entitlementGroupIDs = `-- name: EntitlementGroupIDs :many
SELECT group_id FROM entitlement_groups WHERE entitlement_id = $1
`

func (q *Queries) EntitlementGroupIDs(ctx context.Context, entitlementID string) ([]string, error) {
	rows, err := q.db.Query(ctx, entitlementGroupIDs, entitlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitlement = `-- name: GetEntitlement :one
SELECT id, store, product_id, store_transaction_id, environment, purchased_at, expires_at, revoked_at FROM entitlements WHERE store = $1 AND store_transaction_id = $2
`

type GetEntitlementParams struct {
	Store              string
	StoreTransactionID string
}

func (q *Queries) GetEntitlement(ctx context.Context, arg GetEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlement, arg.Store, arg.StoreTransactionID)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Store,
		&i.ProductID,
		&i.StoreTransactionID,
		&i.Environment,
		&i.PurchasedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const linkEntitlementUser = `-- name: LinkEntitlementUser :exec
INSERT INTO entitlement_users (entitlement_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkEntitlementUserParams struct {
	EntitlementID string
	UserID        string
}

func (q *Queries) LinkEntitlementUser(ctx context.Context, arg LinkEntitlementUserParams) error {
	_, err := q.db.Exec(ctx, linkEntitlementUser, arg.EntitlementID, arg.UserID)
	return err
}

const refreshPremium = `-- name: RefreshPremium :many
UPDATE groups g SET premium = NOT g.premium
WHERE g.id = ANY($1::text[])
    AND g.premium <> EXISTS (
        SELECT 1 FROM entitlement_groups eg
        JOIN entitlements e ON e.id = eg.entitlement_id
        WHERE eg.group_id = g.id AND e.revoked_at IS NULL
    )
RETURNING id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by, premium
`

// Sets groups.premium to whether a live entitlement unlocked the group and
// returns the groups it changed.
func (q *Queries) RefreshPremium(ctx context.Context, groupIds []string) ([]Group, error) {
	rows, err := q.db.Query(ctx, refreshPremium, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CustomSportName,
			&i.InviteCode,
			&i.Name,
			&i.SportPreset,
			&i.ActiveSeasonID,
			&i.AssetIDWallpaper,
			&i.CreatedBy,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEntitlement = `-- name: SaveEntitlement :one
INSERT INTO entitlements (id, store, product_id, store_transaction_id, environment, purchased_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (store, store_transaction_id) DO UPDATE SET store = EXCLUDED.store
RETURNING id, store, product_id, store_transaction_id, environment, purchased_at, expires_at, revoked_at
`

type SaveEntitlementParams struct {
	ID                 string
	Store              string
	ProductID          string
	StoreTransactionID string
	Environment        string
	PurchasedAt        time.Time
	ExpiresAt          *time.Time
}

// A purchase seen again (another device, a restore) keeps its row: only the
// store's notifications change whether it is revoked, so replaying an old
// signed purchase can't undo a refund.
func (q *Queries) SaveEntitlement(ctx context.Context, arg SaveEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, saveEntitlement,
		arg.ID,
		arg.Store,
		arg.ProductID,
		arg.StoreTransactionID,
		arg.Environment,
		arg.PurchasedAt,
		arg.ExpiresAt,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Store,
		&i.ProductID,
		&i.StoreTransactionID,
		&i.Environment,
		&i.PurchasedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const setEntitlementRevoked = `-- name: SetEntitlementRevoked :exec
UPDATE entitlements SET revoked_at = $2 WHERE id = $1
`

type SetEntitlementRevokedParams struct {
	ID        string
	RevokedAt *time.Time
}

func (q *Queries) SetEntitlementRevoked(ctx context.Context, arg SetEntitlementRevokedParams) error {
	_, err := q.db.Exec(ctx, setEntitlementRevoked, arg.ID, arg.RevokedAt)
	return err
}

const unlockGroups = `-- name: UnlockGroups :exec
INSERT INTO entitlement_groups (entitlement_id, group_id)
SELECT $1::text, g.id FROM groups g
WHERE g.id = $2::text
    OR g.created_by IN (
        SELECT gm.id FROM group_members gm
        JOIN entitlement_users eu ON eu.user_id = gm.user_id
        WHERE eu.entitlement_id = $1::text
    )
ON CONFLICT DO NOTHING
`

type UnlockGroupsParams struct {
	EntitlementID string
	GroupID       *string
}

// An entitlement unlocks every group a linked install created, and the group
// the buyer was in when buying (group_id, null otherwise).
func (q *Queries) UnlockGroups(ctx context.Context, arg UnlockGroupsParams) error {
	_, err := q.db.Exec(ctx, unlockGroups, arg.EntitlementID, arg.GroupID)
	return err
}

const unlockNewGroup = `-- name: UnlockNewGroup :exec
INSERT INTO entitlement_groups (entitlement_id, group_id)
SELECT eu.entitlement_id, $1::text FROM entitlement_users eu
JOIN entitlements e ON e.id = eu.entitlement_id
WHERE eu.user_id = $2::text AND e.revoked_at IS NULL
`

type UnlockNewGroupParams struct {
	GroupID string
	UserID  string
}

// A group created by an install linked to a live entitlement.
func (q *Queries) UnlockNewGroup(ctx context.Context, arg UnlockNewGroupParams) error {
	_, err := q.db.Exec(ctx, unlockNewGroup, arg.GroupID, arg.UserID)
	return err
}
