// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package db

import (
	"context"
	"time"
)

const forgetActivityStartToken = `-- name: ForgetActivityStartToken :exec
UPDATE push_tokens SET activity_start_token = NULL WHERE user_id = $1 AND activity_start_token = $2
`

type ForgetActivityStartTokenParams struct {
	UserID             string
	ActivityStartToken *string
}

func (q *Queries) ForgetActivityStartToken(ctx context.Context, arg ForgetActivityStartTokenParams) error {
	_, err := q.db.Exec(ctx, forgetActivityStartToken, arg.UserID, arg.ActivityStartToken)
	return err
}

const forgetDeviceToken = `-- name: ForgetDeviceToken :exec
UPDATE push_tokens SET device_token = NULL WHERE user_id = $1 AND device_token = $2
`

type ForgetDeviceTokenParams struct {
	UserID      string
	DeviceToken *string
}

func (q *Queries) ForgetDeviceToken(ctx context.Context, arg ForgetDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, forgetDeviceToken, arg.UserID, arg.DeviceToken)
	return err
}

const groupPushTokens = `-- name: GroupPushTokens :many
SELECT pt.user_id, pt.device_token, pt.activity_start_token
FROM push_tokens pt
JOIN group_members gm ON gm.user_id = pt.user_id
WHERE gm.group_id = $1 AND gm.active
`

type GroupPushTokensRow struct {
	UserID             string
	DeviceToken        *string
	ActivityStartToken *string
}

// The tokens of the group's active members' phones.
func (q *Queries) GroupPushTokens(ctx context.Context, groupID *string) ([]GroupPushTokensRow, error) {
	rows, err := q.db.Query(ctx, groupPushTokens, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupPushTokensRow
	for rows.Next() {
		var i GroupPushTokensRow
		if err := rows.Scan(&i.UserID, &i.DeviceToken, &i.ActivityStartToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLiveMatchActivityChannel = `-- name: SetLiveMatchActivityChannel :execrows
UPDATE live_matches SET activity_channel = $2 WHERE id = $1 AND activity_channel IS NULL
`

type SetLiveMatchActivityChannelParams struct {
	ID              string
	ActivityChannel *string
}

// Only the first channel sticks, so a live match's activities start once.
func (q *Queries) SetLiveMatchActivityChannel(ctx context.Context, arg SetLiveMatchActivityChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLiveMatchActivityChannel, arg.ID, arg.ActivityChannel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLiveMatchActivityEnded = `-- name: SetLiveMatchActivityEnded :exec
UPDATE live_matches SET activity_ended = true WHERE id = $1
`

func (q *Queries) SetLiveMatchActivityEnded(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setLiveMatchActivityEnded, id)
	return err
}

const setLiveMatchDisplay = `-- name: SetLiveMatchDisplay :exec
UPDATE live_matches SET display = $2, display_seq = $3 WHERE id = $1
`

type SetLiveMatchDisplayParams struct {
	ID         string
	Display    *string
	DisplaySeq *int64
}

func (q *Queries) SetLiveMatchDisplay(ctx context.Context, arg SetLiveMatchDisplayParams) error {
	_, err := q.db.Exec(ctx, setLiveMatchDisplay, arg.ID, arg.Display, arg.DisplaySeq)
	return err
}

const upsertPushTokens = `-- name: UpsertPushTokens :exec
INSERT INTO push_tokens (user_id, device_token, activity_start_token, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET device_token = EXCLUDED.device_token,
    activity_start_token = EXCLUDED.activity_start_token,
    updated_at = EXCLUDED.updated_at
`

type UpsertPushTokensParams struct {
	UserID             string
	DeviceToken        *string
	ActivityStartToken *string
	UpdatedAt          time.Time
}

func (q *Queries) UpsertPushTokens(ctx context.Context, arg UpsertPushTokensParams) error {
	_, err := q.db.Exec(ctx, upsertPushTokens,
		arg.UserID,
		arg.DeviceToken,
		arg.ActivityStartToken,
		arg.UpdatedAt,
	)
	return err
}
