// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recordings.sql

package db

import (
	"context"
	"time"
)

const cameraRecordingMatchIDs = `-- name: CameraRecordingMatchIDs :many
SELECT live_match_id FROM camera_recording_matches WHERE recording_id = $1 ORDER BY live_match_id
`

func (q *Queries) CameraRecordingMatchIDs(ctx context.Context, recordingID string) ([]string, error) {
	rows, err := q.db.Query(ctx, cameraRecordingMatchIDs, recordingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var live_match_id string
		if err := rows.Scan(&live_match_id); err != nil {
			return nil, err
		}
		items = append(items, live_match_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCameraRecording = `-- name: CompleteCameraRecording :execrows
UPDATE camera_recordings SET uploaded_at = COALESCE(uploaded_at, $4)
WHERE id = $1 AND group_id = $2 AND created_by = $3
`

type CompleteCameraRecordingParams struct {
	ID         string
	GroupID    string
	CreatedBy  string
	UploadedAt *time.Time
}

func (q *Queries) CompleteCameraRecording(ctx context.Context, arg CompleteCameraRecordingParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCameraRecording,
		arg.ID,
		arg.GroupID,
		arg.CreatedBy,
		arg.UploadedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCameraRecording = `-- name: DeleteCameraRecording :exec
DELETE FROM camera_recordings WHERE id = $1 AND group_id = $2
`

type DeleteCameraRecordingParams struct {
	ID      string
	GroupID string
}

func (q *Queries) DeleteCameraRecording(ctx context.Context, arg DeleteCameraRecordingParams) error {
	_, err := q.db.Exec(ctx, deleteCameraRecording, arg.ID, arg.GroupID)
	return err
}

const getCameraRecording = `-- name: GetCameraRecording :one
SELECT id, group_id, created_by, camera_id, camera_name, session_id, segment_index, started_at, ended_at, content_type, size_bytes, object_key, created_at, uploaded_at FROM camera_recordings WHERE id = $1 AND group_id = $2 FOR UPDATE
`

type GetCameraRecordingParams struct {
	ID      string
	GroupID string
}

func (q *Queries) GetCameraRecording(ctx context.Context, arg GetCameraRecordingParams) (CameraRecording, error) {
	row := q.db.QueryRow(ctx, getCameraRecording, arg.ID, arg.GroupID)
	var i CameraRecording
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.CameraID,
		&i.CameraName,
		&i.SessionID,
		&i.SegmentIndex,
		&i.StartedAt,
		&i.EndedAt,
		&i.ContentType,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.UploadedAt,
	)
	return i, err
}

const insertCameraRecording = `-- name: InsertCameraRecording :execrows
INSERT INTO camera_recordings (id, group_id, created_by, camera_id, camera_name, session_id, segment_index, started_at, ended_at, content_type, size_bytes, object_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT DO NOTHING
`

type InsertCameraRecordingParams struct {
	ID           string
	GroupID      string
	CreatedBy    string
	CameraID     string
	CameraName   string
	SessionID    string
	SegmentIndex int32
	StartedAt    time.Time
	EndedAt      time.Time
	ContentType  string
	SizeBytes    int64
	ObjectKey    string
	CreatedAt    time.Time
}

func (q *Queries) InsertCameraRecording(ctx context.Context, arg InsertCameraRecordingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCameraRecording,
		arg.ID,
		arg.GroupID,
		arg.CreatedBy,
		arg.CameraID,
		arg.CameraName,
		arg.SessionID,
		arg.SegmentIndex,
		arg.StartedAt,
		arg.EndedAt,
		arg.ContentType,
		arg.SizeBytes,
		arg.ObjectKey,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkCameraRecordingMatches = `-- name: LinkCameraRecordingMatches :execrows
INSERT INTO camera_recording_matches (recording_id, live_match_id, season_id)
SELECT $1::text, id, season_id FROM live_matches
WHERE group_id = $2::text AND id = ANY ($3::text[])
`

type LinkCameraRecordingMatchesParams struct {
	RecordingID  string
	GroupID      string
	LiveMatchIds []string
}

func (q *Queries) LinkCameraRecordingMatches(ctx context.Context, arg LinkCameraRecordingMatchesParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkCameraRecordingMatches, arg.RecordingID, arg.GroupID, arg.LiveMatchIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
