// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package db

import (
	"context"
)

const clearDefaultRuleMove = `-- name: ClearDefaultRuleMove :exec
UPDATE rule_moves SET default_move = false WHERE season_id = $1 AND default_move
`

func (q *Queries) ClearDefaultRuleMove(ctx context.Context, seasonID *string) error {
	_, err := q.db.Exec(ctx, clearDefaultRuleMove, seasonID)
	return err
}

const copyRules = `-- name: CopyRules :exec
INSERT INTO rules (id, title, description, season_id, created_by, position)
SELECT gen_random_uuid()::text, r.title, r.description, $1, r.created_by,
       (row_number() OVER (ORDER BY r.position NULLS LAST, r.ctid) - 1)::integer
FROM rules r
WHERE r.season_id = $2
`

type CopyRulesParams struct {
	NewSeasonID *string
	OldSeasonID *string
}

func (q *Queries) CopyRules(ctx context.Context, arg CopyRulesParams) error {
	_, err := q.db.Exec(ctx, copyRules, arg.NewSeasonID, arg.OldSeasonID)
	return err
}

const countRuleMovesInSeason = `-- name: CountRuleMovesInSeason :one
SELECT count(*) FROM rule_moves WHERE id = ANY ($2::text[]) AND season_id = $1
`

type CountRuleMovesInSeasonParams struct {
	SeasonID *string
	Ids      []string
}

func (q *Queries) CountRuleMovesInSeason(ctx context.Context, arg CountRuleMovesInSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRuleMovesInSeason, arg.SeasonID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRulesBySeason = `-- name: DeleteRulesBySeason :exec
DELETE FROM rules WHERE season_id = $1
`

func (q *Queries) DeleteRulesBySeason(ctx context.Context, seasonID *string) error {
	_, err := q.db.Exec(ctx, deleteRulesBySeason, seasonID)
	return err
}

const finishingMoveIDs = `-- name: FinishingMoveIDs :many
SELECT id FROM rule_moves WHERE id = ANY ($1::text[]) AND finishing_move
`

func (q *Queries) FinishingMoveIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, finishingMoveIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRuleMove = `-- name: GetRuleMove :one
SELECT id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move FROM rule_moves WHERE id = $1
`

func (q *Queries) GetRuleMove(ctx context.Context, id string) (RuleMove, error) {
	row := q.db.QueryRow(ctx, getRuleMove, id)
	var i RuleMove
	err := row.Scan(
		&i.ID,
		&i.FinishingMove,
		&i.Name,
		&i.PointsForScorer,
		&i.PointsForTeam,
		&i.SeasonID,
		&i.Cups,
		&i.DefaultMove,
	)
	return i, err
}

const insertRuleMove = `-- name: InsertRuleMove :one
INSERT INTO rule_moves (id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move
`

type InsertRuleMoveParams struct {
	ID              string
	FinishingMove   bool
	Name            *string
	PointsForScorer int32
	PointsForTeam   int32
	SeasonID        *string
	Cups            *int32
	DefaultMove     bool
}

func (q *Queries) InsertRuleMove(ctx context.Context, arg InsertRuleMoveParams) (RuleMove, error) {
	row := q.db.QueryRow(ctx, insertRuleMove,
		arg.ID,
		arg.FinishingMove,
		arg.Name,
		arg.PointsForScorer,
		arg.PointsForTeam,
		arg.SeasonID,
		arg.Cups,
		arg.DefaultMove,
	)
	var i RuleMove
	err := row.Scan(
		&i.ID,
		&i.FinishingMove,
		&i.Name,
		&i.PointsForScorer,
		&i.PointsForTeam,
		&i.SeasonID,
		&i.Cups,
		&i.DefaultMove,
	)
	return i, err
}

type InsertRuleMovesParams struct {
	ID              string
	FinishingMove   bool
	Name            *string
	PointsForScorer int32
	PointsForTeam   int32
	SeasonID        *string
	Cups            *int32
	DefaultMove     bool
}

type InsertRulesParams struct {
	ID          string
	Title       *string
	Description *string
	SeasonID    *string
	CreatedBy   *string
	Position    *int32
}

const ruleMoveExistsInSeason = `-- name: RuleMoveExistsInSeason :one
SELECT EXISTS (SELECT 1 FROM rule_moves WHERE id = $1 AND season_id = $2)
`

type RuleMoveExistsInSeasonParams struct {
	ID       string
	SeasonID *string
}

func (q *Queries) RuleMoveExistsInSeason(ctx context.Context, arg RuleMoveExistsInSeasonParams) (bool, error) {
	row := q.db.QueryRow(ctx, ruleMoveExistsInSeason, arg.ID, arg.SeasonID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ruleMovesByIDs = `-- name: RuleMovesByIDs :many
SELECT id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move FROM rule_moves WHERE id = ANY ($1::text[])
`

func (q *Queries) RuleMovesByIDs(ctx context.Context, ids []string) ([]RuleMove, error) {
	rows, err := q.db.Query(ctx, ruleMovesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleMove
	for rows.Next() {
		var i RuleMove
		if err := rows.Scan(
			&i.ID,
			&i.FinishingMove,
			&i.Name,
			&i.PointsForScorer,
			&i.PointsForTeam,
			&i.SeasonID,
			&i.Cups,
			&i.DefaultMove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleMovesBySeason = `-- name: RuleMovesBySeason :many
SELECT id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move FROM rule_moves WHERE season_id = $1 ORDER BY ctid
`

func (q *Queries) RuleMovesBySeason(ctx context.Context, seasonID *string) ([]RuleMove, error) {
	rows, err := q.db.Query(ctx, ruleMovesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleMove
	for rows.Next() {
		var i RuleMove
		if err := rows.Scan(
			&i.ID,
			&i.FinishingMove,
			&i.Name,
			&i.PointsForScorer,
			&i.PointsForTeam,
			&i.SeasonID,
			&i.Cups,
			&i.DefaultMove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rulesBySeason = `-- name: RulesBySeason :many
SELECT id, description, title, season_id, created_by, position FROM rules WHERE season_id = $1 ORDER BY position NULLS LAST, ctid
`

func (q *Queries) RulesBySeason(ctx context.Context, seasonID *string) ([]Rule, error) {
	rows, err := q.db.Query(ctx, rulesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Title,
			&i.SeasonID,
			&i.CreatedBy,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleMove = `-- name: UpdateRuleMove :one
UPDATE rule_moves SET name = $2, points_for_team = $3, points_for_scorer = $4, finishing_move = $5, cups = $6, default_move = $7
WHERE id = $1
RETURNING id, finishing_move, name, points_for_scorer, points_for_team, season_id, cups, default_move
`

type UpdateRuleMoveParams struct {
	ID              string
	Name            *string
	PointsForTeam   int32
	PointsForScorer int32
	FinishingMove   bool
	Cups            *int32
	DefaultMove     bool
}

func (q *Queries) UpdateRuleMove(ctx context.Context, arg UpdateRuleMoveParams) (RuleMove, error) {
	row := q.db.QueryRow(ctx, updateRuleMove,
		arg.ID,
		arg.Name,
		arg.PointsForTeam,
		arg.PointsForScorer,
		arg.FinishingMove,
		arg.Cups,
		arg.DefaultMove,
	)
	var i RuleMove
	err := row.Scan(
		&i.ID,
		&i.FinishingMove,
		&i.Name,
		&i.PointsForScorer,
		&i.PointsForTeam,
		&i.SeasonID,
		&i.Cups,
		&i.DefaultMove,
	)
	return i, err
}
