// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package db

import (
	"context"
	"time"
)

const activeTournamentExists = `-- name: ActiveTournamentExists :one
SELECT EXISTS (SELECT 1 FROM tournaments WHERE group_id = $1 AND status = 'ACTIVE')
`

func (q *Queries) ActiveTournamentExists(ctx context.Context, groupID string) (bool, error) {
	row := q.db.QueryRow(ctx, activeTournamentExists, groupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTournament = `-- name: GetTournament :one
SELECT id, group_id, season_id, status, created_at, data FROM tournaments WHERE id = $1 AND group_id = $2
`

type GetTournamentParams struct {
	ID      string
	GroupID string
}

func (q *Queries) GetTournament(ctx context.Context, arg GetTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, arg.ID, arg.GroupID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Status,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const insertTournament = `-- name: InsertTournament :execrows
INSERT INTO tournaments (id, group_id, season_id, status, created_at, data)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type InsertTournamentParams struct {
	ID        string
	GroupID   string
	SeasonID  string
	Status    string
	CreatedAt time.Time
	Data      []byte
}

func (q *Queries) InsertTournament(ctx context.Context, arg InsertTournamentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTournament,
		arg.ID,
		arg.GroupID,
		arg.SeasonID,
		arg.Status,
		arg.CreatedAt,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkLiveTournament = `-- name: LinkLiveTournament :exec
UPDATE live_matches SET tournament_id = $2, tournament_stage = $3 WHERE id = $1
`

type LinkLiveTournamentParams struct {
	ID              string
	TournamentID    *string
	TournamentStage *string
}

func (q *Queries) LinkLiveTournament(ctx context.Context, arg LinkLiveTournamentParams) error {
	_, err := q.db.Exec(ctx, linkLiveTournament, arg.ID, arg.TournamentID, arg.TournamentStage)
	return err
}

const linkMatchTournament = `-- name: LinkMatchTournament :exec
UPDATE matches SET tournament_id = $2, tournament_stage = $3 WHERE id = $1
`

type LinkMatchTournamentParams struct {
	ID              string
	TournamentID    *string
	TournamentStage *string
}

func (q *Queries) LinkMatchTournament(ctx context.Context, arg LinkMatchTournamentParams) error {
	_, err := q.db.Exec(ctx, linkMatchTournament, arg.ID, arg.TournamentID, arg.TournamentStage)
	return err
}

const lockTournament = `-- name: LockTournament :one
SELECT id, group_id, season_id, status, created_at, data FROM tournaments WHERE id = $1 AND group_id = $2 FOR UPDATE
`

type LockTournamentParams struct {
	ID      string
	GroupID string
}

func (q *Queries) LockTournament(ctx context.Context, arg LockTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, lockTournament, arg.ID, arg.GroupID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Status,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const lockTournamentGroup = `-- name: LockTournamentGroup :one
SELECT id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by FROM groups WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTournamentGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, lockTournamentGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const saveTournament = `-- name: SaveTournament :exec
UPDATE tournaments SET data = $2, status = $3 WHERE id = $1
`

type SaveTournamentParams struct {
	ID     string
	Data   []byte
	Status string
}

func (q *Queries) SaveTournament(ctx context.Context, arg SaveTournamentParams) error {
	_, err := q.db.Exec(ctx, saveTournament, arg.ID, arg.Data, arg.Status)
	return err
}

const tournamentForFixture = `-- name: TournamentForFixture :one
SELECT t.id, t.group_id, t.season_id, t.status, t.created_at, t.data FROM tournaments t
WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(t.data->'stages') stage,
    jsonb_array_elements(stage->'matches') fixture WHERE fixture->>'id' = $1::text
)
`

func (q *Queries) TournamentForFixture(ctx context.Context, fixtureID string) (Tournament, error) {
	row := q.db.QueryRow(ctx, tournamentForFixture, fixtureID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SeasonID,
		&i.Status,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const tournamentsByGroup = `-- name: TournamentsByGroup :many
SELECT id, group_id, season_id, status, created_at, data FROM tournaments WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) TournamentsByGroup(ctx context.Context, groupID string) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, tournamentsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SeasonID,
			&i.Status,
			&i.CreatedAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
