// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vision_hits.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendVisionHitFeedback = `-- name: AppendVisionHitFeedback :exec
INSERT INTO vision_hit_feedback (hit_id, revision, actor_user_id, label, source, reviewer_model, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendVisionHitFeedbackParams struct {
	HitID         string
	Revision      int32
	ActorUserID   string
	Label         string
	Source        string
	ReviewerModel *string
	Reason        *string
	CreatedAt     time.Time
}

func (q *Queries) AppendVisionHitFeedback(ctx context.Context, arg AppendVisionHitFeedbackParams) error {
	_, err := q.db.Exec(ctx, appendVisionHitFeedback,
		arg.HitID,
		arg.Revision,
		arg.ActorUserID,
		arg.Label,
		arg.Source,
		arg.ReviewerModel,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const consumeVisionCameraRate = `-- name: ConsumeVisionCameraRate :execrows
UPDATE vision_cameras
SET rate_window = CASE WHEN rate_window <= $3::timestamptz - interval '1 minute' THEN $3::timestamptz ELSE rate_window END,
    rate_count = CASE WHEN rate_window <= $3::timestamptz - interval '1 minute' THEN 1 ELSE rate_count + 1 END,
    last_hit_at = $3::timestamptz
WHERE group_id = $1 AND camera_id = $2
AND last_hit_at <= $3::timestamptz - interval '250 milliseconds'
AND (rate_window <= $3::timestamptz - interval '1 minute' OR rate_count < 60)
`

type ConsumeVisionCameraRateParams struct {
	GroupID  string
	CameraID string
	Now      pgtype.Timestamptz
}

func (q *Queries) ConsumeVisionCameraRate(ctx context.Context, arg ConsumeVisionCameraRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVisionCameraRate, arg.GroupID, arg.CameraID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVisionHit = `-- name: DeleteVisionHit :exec
DELETE FROM vision_hits WHERE id = $1 AND group_id = $2
`

type DeleteVisionHitParams struct {
	ID      string
	GroupID string
}

func (q *Queries) DeleteVisionHit(ctx context.Context, arg DeleteVisionHitParams) error {
	_, err := q.db.Exec(ctx, deleteVisionHit, arg.ID, arg.GroupID)
	return err
}

const getVisionCameraSession = `-- name: GetVisionCameraSession :one
SELECT group_id, session_id, camera_id, created_by FROM vision_camera_sessions WHERE group_id = $1 AND session_id = $2
`

type GetVisionCameraSessionParams struct {
	GroupID   string
	SessionID string
}

func (q *Queries) GetVisionCameraSession(ctx context.Context, arg GetVisionCameraSessionParams) (VisionCameraSession, error) {
	row := q.db.QueryRow(ctx, getVisionCameraSession, arg.GroupID, arg.SessionID)
	var i VisionCameraSession
	err := row.Scan(
		&i.GroupID,
		&i.SessionID,
		&i.CameraID,
		&i.CreatedBy,
	)
	return i, err
}

const getVisionHit = `-- name: GetVisionHit :one
SELECT id, group_id, live_match_id, camera_id, session_id, created_by, camera_occurred_at, proposal, created_at, revision, label, feedback_source, reviewer_model, reason, reviewed_at, last_replay_requested_at FROM vision_hits WHERE id = $1 AND group_id = $2
`

type GetVisionHitParams struct {
	ID      string
	GroupID string
}

func (q *Queries) GetVisionHit(ctx context.Context, arg GetVisionHitParams) (VisionHit, error) {
	row := q.db.QueryRow(ctx, getVisionHit, arg.ID, arg.GroupID)
	var i VisionHit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.LiveMatchID,
		&i.CameraID,
		&i.SessionID,
		&i.CreatedBy,
		&i.CameraOccurredAt,
		&i.Proposal,
		&i.CreatedAt,
		&i.Revision,
		&i.Label,
		&i.FeedbackSource,
		&i.ReviewerModel,
		&i.Reason,
		&i.ReviewedAt,
		&i.LastReplayRequestedAt,
	)
	return i, err
}

const getVisionHitFeedback = `-- name: GetVisionHitFeedback :one
SELECT hit_id, revision, actor_user_id, label, source, reviewer_model, reason, created_at FROM vision_hit_feedback WHERE hit_id = $1 AND revision = $2
`

type GetVisionHitFeedbackParams struct {
	HitID    string
	Revision int32
}

func (q *Queries) GetVisionHitFeedback(ctx context.Context, arg GetVisionHitFeedbackParams) (VisionHitFeedback, error) {
	row := q.db.QueryRow(ctx, getVisionHitFeedback, arg.HitID, arg.Revision)
	var i VisionHitFeedback
	err := row.Scan(
		&i.HitID,
		&i.Revision,
		&i.ActorUserID,
		&i.Label,
		&i.Source,
		&i.ReviewerModel,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertVisionCamera = `-- name: InsertVisionCamera :exec
INSERT INTO vision_cameras (group_id, camera_id, created_by) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertVisionCameraParams struct {
	GroupID   string
	CameraID  string
	CreatedBy string
}

func (q *Queries) InsertVisionCamera(ctx context.Context, arg InsertVisionCameraParams) error {
	_, err := q.db.Exec(ctx, insertVisionCamera, arg.GroupID, arg.CameraID, arg.CreatedBy)
	return err
}

const insertVisionCameraSession = `-- name: InsertVisionCameraSession :exec
INSERT INTO vision_camera_sessions (group_id, session_id, camera_id, created_by) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertVisionCameraSessionParams struct {
	GroupID   string
	SessionID string
	CameraID  string
	CreatedBy string
}

func (q *Queries) InsertVisionCameraSession(ctx context.Context, arg InsertVisionCameraSessionParams) error {
	_, err := q.db.Exec(ctx, insertVisionCameraSession,
		arg.GroupID,
		arg.SessionID,
		arg.CameraID,
		arg.CreatedBy,
	)
	return err
}

const insertVisionHit = `-- name: InsertVisionHit :execrows
INSERT INTO vision_hits (id, group_id, live_match_id, camera_id, session_id, created_by, camera_occurred_at, proposal, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING
`

type InsertVisionHitParams struct {
	ID               string
	GroupID          string
	LiveMatchID      string
	CameraID         string
	SessionID        string
	CreatedBy        string
	CameraOccurredAt time.Time
	Proposal         []byte
	CreatedAt        time.Time
}

func (q *Queries) InsertVisionHit(ctx context.Context, arg InsertVisionHitParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVisionHit,
		arg.ID,
		arg.GroupID,
		arg.LiveMatchID,
		arg.CameraID,
		arg.SessionID,
		arg.CreatedBy,
		arg.CameraOccurredAt,
		arg.Proposal,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVisionHits = `-- name: ListVisionHits :many
SELECT id, group_id, live_match_id, camera_id, session_id, created_by, camera_occurred_at, proposal, created_at, revision, label, feedback_source, reviewer_model, reason, reviewed_at, last_replay_requested_at FROM vision_hits
WHERE group_id = $1::text
AND ($2::text = '' OR live_match_id = $2::text)
AND (NOT $3::boolean OR label = 'uncertain' OR (label = 'unreviewed' AND created_at < $4::timestamptz))
AND (NOT $5::boolean OR label IN ('accepted', 'declined'))
AND (NOT $6::boolean OR (created_at, id) < ($7::timestamptz, $8::text))
ORDER BY created_at DESC, id DESC LIMIT $9::integer
`

type ListVisionHitsParams struct {
	GroupID      string
	LiveMatchID  string
	Review       bool
	ReviewBefore pgtype.Timestamptz
	Training     bool
	HasCursor    bool
	BeforeTime   pgtype.Timestamptz
	BeforeID     string
	PageLimit    int32
}

func (q *Queries) ListVisionHits(ctx context.Context, arg ListVisionHitsParams) ([]VisionHit, error) {
	rows, err := q.db.Query(ctx, listVisionHits,
		arg.GroupID,
		arg.LiveMatchID,
		arg.Review,
		arg.ReviewBefore,
		arg.Training,
		arg.HasCursor,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisionHit
	for rows.Next() {
		var i VisionHit
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.LiveMatchID,
			&i.CameraID,
			&i.SessionID,
			&i.CreatedBy,
			&i.CameraOccurredAt,
			&i.Proposal,
			&i.CreatedAt,
			&i.Revision,
			&i.Label,
			&i.FeedbackSource,
			&i.ReviewerModel,
			&i.Reason,
			&i.ReviewedAt,
			&i.LastReplayRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVisionCamera = `-- name: LockVisionCamera :one
SELECT group_id, camera_id, created_by, rate_window, rate_count, last_hit_at FROM vision_cameras WHERE group_id = $1 AND camera_id = $2 FOR UPDATE
`

type LockVisionCameraParams struct {
	GroupID  string
	CameraID string
}

func (q *Queries) LockVisionCamera(ctx context.Context, arg LockVisionCameraParams) (VisionCamera, error) {
	row := q.db.QueryRow(ctx, lockVisionCamera, arg.GroupID, arg.CameraID)
	var i VisionCamera
	err := row.Scan(
		&i.GroupID,
		&i.CameraID,
		&i.CreatedBy,
		&i.RateWindow,
		&i.RateCount,
		&i.LastHitAt,
	)
	return i, err
}

const lockVisionHit = `-- name: LockVisionHit :one
SELECT id, group_id, live_match_id, camera_id, session_id, created_by, camera_occurred_at, proposal, created_at, revision, label, feedback_source, reviewer_model, reason, reviewed_at, last_replay_requested_at FROM vision_hits WHERE id = $1 AND group_id = $2 FOR UPDATE
`

type LockVisionHitParams struct {
	ID      string
	GroupID string
}

func (q *Queries) LockVisionHit(ctx context.Context, arg LockVisionHitParams) (VisionHit, error) {
	row := q.db.QueryRow(ctx, lockVisionHit, arg.ID, arg.GroupID)
	var i VisionHit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.LiveMatchID,
		&i.CameraID,
		&i.SessionID,
		&i.CreatedBy,
		&i.CameraOccurredAt,
		&i.Proposal,
		&i.CreatedAt,
		&i.Revision,
		&i.Label,
		&i.FeedbackSource,
		&i.ReviewerModel,
		&i.Reason,
		&i.ReviewedAt,
		&i.LastReplayRequestedAt,
	)
	return i, err
}

const recentVisionHitDuplicate = `-- name: RecentVisionHitDuplicate :one
SELECT EXISTS (SELECT 1 FROM vision_hits
WHERE group_id = $1 AND camera_id = $2 AND live_match_id = $3 AND session_id = $4
AND camera_occurred_at BETWEEN $5::timestamptz - interval '2 seconds' AND $5::timestamptz + interval '2 seconds'
AND proposal->>'team' = $6::text AND proposal->'cup' = $7::jsonb)
`

type RecentVisionHitDuplicateParams struct {
	GroupID     string
	CameraID    string
	LiveMatchID string
	SessionID   string
	EventTime   pgtype.Timestamptz
	Team        string
	Cup         []byte
}

func (q *Queries) RecentVisionHitDuplicate(ctx context.Context, arg RecentVisionHitDuplicateParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentVisionHitDuplicate,
		arg.GroupID,
		arg.CameraID,
		arg.LiveMatchID,
		arg.SessionID,
		arg.EventTime,
		arg.Team,
		arg.Cup,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const requestVisionHitReplay = `-- name: RequestVisionHitReplay :execrows
UPDATE vision_hits SET last_replay_requested_at = $3::timestamptz
WHERE id = $1 AND group_id = $2
AND (last_replay_requested_at IS NULL OR last_replay_requested_at <= $3::timestamptz - interval '5 seconds')
`

type RequestVisionHitReplayParams struct {
	ID      string
	GroupID string
	Now     pgtype.Timestamptz
}

func (q *Queries) RequestVisionHitReplay(ctx context.Context, arg RequestVisionHitReplayParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestVisionHitReplay, arg.ID, arg.GroupID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVisionHitFeedback = `-- name: SetVisionHitFeedback :one
UPDATE vision_hits SET revision = revision + 1, label = $4, feedback_source = $5,
reviewer_model = $6, reason = $7, reviewed_at = $8
WHERE id = $1 AND group_id = $2 AND revision = $3 RETURNING id, group_id, live_match_id, camera_id, session_id, created_by, camera_occurred_at, proposal, created_at, revision, label, feedback_source, reviewer_model, reason, reviewed_at, last_replay_requested_at
`

type SetVisionHitFeedbackParams struct {
	ID             string
	GroupID        string
	Revision       int32
	Label          string
	FeedbackSource *string
	ReviewerModel  *string
	Reason         *string
	ReviewedAt     *time.Time
}

func (q *Queries) SetVisionHitFeedback(ctx context.Context, arg SetVisionHitFeedbackParams) (VisionHit, error) {
	row := q.db.QueryRow(ctx, setVisionHitFeedback,
		arg.ID,
		arg.GroupID,
		arg.Revision,
		arg.Label,
		arg.FeedbackSource,
		arg.ReviewerModel,
		arg.Reason,
		arg.ReviewedAt,
	)
	var i VisionHit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.LiveMatchID,
		&i.CameraID,
		&i.SessionID,
		&i.CreatedBy,
		&i.CameraOccurredAt,
		&i.Proposal,
		&i.CreatedAt,
		&i.Revision,
		&i.Label,
		&i.FeedbackSource,
		&i.ReviewerModel,
		&i.Reason,
		&i.ReviewedAt,
		&i.LastReplayRequestedAt,
	)
	return i, err
}

const visionHitReplaySegments = `-- name: VisionHitReplaySegments :many
SELECT cr.id, cr.group_id, cr.created_by, cr.camera_id, cr.camera_name, cr.session_id, cr.segment_index, cr.started_at, cr.ended_at, cr.content_type, cr.size_bytes, cr.object_key, cr.created_at, cr.uploaded_at FROM camera_recordings cr
JOIN camera_recording_matches crm ON crm.recording_id = cr.id
WHERE cr.group_id = $1 AND crm.live_match_id = $2 AND cr.camera_id = $3 AND cr.session_id = $4
AND cr.created_by = $5 AND cr.uploaded_at IS NOT NULL
AND cr.started_at < $6::timestamptz AND cr.ended_at > $7::timestamptz
ORDER BY cr.started_at, cr.ended_at, cr.id LIMIT 64 FOR SHARE OF cr
`

type VisionHitReplaySegmentsParams struct {
	GroupID     string
	LiveMatchID string
	CameraID    string
	SessionID   string
	CreatedBy   string
	ToTime      pgtype.Timestamptz
	FromTime    pgtype.Timestamptz
}

func (q *Queries) VisionHitReplaySegments(ctx context.Context, arg VisionHitReplaySegmentsParams) ([]CameraRecording, error) {
	rows, err := q.db.Query(ctx, visionHitReplaySegments,
		arg.GroupID,
		arg.LiveMatchID,
		arg.CameraID,
		arg.SessionID,
		arg.CreatedBy,
		arg.ToTime,
		arg.FromTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CameraRecording
	for rows.Next() {
		var i CameraRecording
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.CameraID,
			&i.CameraName,
			&i.SessionID,
			&i.SegmentIndex,
			&i.StartedAt,
			&i.EndedAt,
			&i.ContentType,
			&i.SizeBytes,
			&i.ObjectKey,
			&i.CreatedAt,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
