openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /groups/{id}:
    get:
      tags:
      - group-controller
      operationId: getGroupById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeGroupDto"
    put:
      tags:
      - group-controller
      operationId: updateGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeGroupDto"
  /groups/{groupId}/seasons/{seasonId}/new-match:
    put:
      tags:
      - match-controller
      operationId: createMatch
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: seasonId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeMatchDto"
  /groups/{groupId}/profiles/{id}:
    get:
      tags:
      - profile-controller
      operationId: getProfileById
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeProfileDto"
    put:
      tags:
      - profile-controller
      operationId: updateProfile
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeProfileDto"
    delete:
      tags:
      - profile-controller
      operationId: deleteProfile
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeVoid"
  /groups/{groupId}/active-season:
    put:
      tags:
      - season-controller
      operationId: startNewSeason
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SeasonCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeSeasonDto"
  /groups:
    get:
      tags:
      - group-controller
      operationId: getAllGroups
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeListGroupDto"
    post:
      tags:
      - group-controller
      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeGroupDto"
  /groups/{groupId}/profiles:
    get:
      tags:
      - profile-controller
      operationId: listAllProfiles
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeListProfileDto"
    post:
      tags:
      - profile-controller
      operationId: createProfile
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeProfileDto"
  /healthcheck:
    get:
      tags:
      - healthcheck-controller
      operationId: getHealthcheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeString"
  /groups/{groupId}/seasons:
    get:
      tags:
      - season-controller
      operationId: getAllSeasons
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeListSeasonDto"
  /groups/{groupId}/seasons/{seasonId}/matches:
    get:
      tags:
      - match-controller
      operationId: getAllMatches
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: seasonId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeListMatchDto"
  /groups/{groupId}/seasons/{seasonId}/matches/{id}:
    get:
      tags:
      - match-controller
      operationId: getMatchById
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: seasonId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeMatchDto"
  /groups/{groupId}/seasons/{id}:
    get:
      tags:
      - season-controller
      operationId: getSeasonById
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseEnvelopeSeasonDto"
components:
  schemas:
    GroupCreateDto:
      type: object
      properties:
        name:
          type: string
    ErrorDetails:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    GroupDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        inviteCode:
          type: string
        groupSettings:
          $ref: "#/components/schemas/GroupSettings"
        activeSeason:
          $ref: "#/components/schemas/Season"
    GroupSettings:
      type: object
      properties:
        id:
          type: string
        settingValue:
          type: string
    ResponseEnvelopeGroupDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          $ref: "#/components/schemas/GroupDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    Season:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        groupId:
          type: string
    MatchDto:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        season:
          $ref: "#/components/schemas/Season"
    ResponseEnvelopeMatchDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          $ref: "#/components/schemas/MatchDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ProfileCreateDto:
      type: object
      properties:
        name:
          type: string
    ProfileDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        groupId:
          type: string
    ResponseEnvelopeProfileDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          $ref: "#/components/schemas/ProfileDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    SeasonCreateDto:
      type: object
      properties:
        oldSeasonName:
          type: string
    ResponseEnvelopeSeasonDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          $ref: "#/components/schemas/SeasonDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    SeasonDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        groupId:
          type: string
    ResponseEnvelopeString:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ResponseEnvelopeListGroupDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: "#/components/schemas/GroupDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ResponseEnvelopeListSeasonDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: "#/components/schemas/SeasonDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ResponseEnvelopeListMatchDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: "#/components/schemas/MatchDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ResponseEnvelopeListProfileDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProfileDto"
        error:
          $ref: "#/components/schemas/ErrorDetails"
    ResponseEnvelopeVoid:
      type: object
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
        httpCode:
          type: integer
          format: int32
        data:
          type: object
        error:
          $ref: "#/components/schemas/ErrorDetails"
