/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/_simulator'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SimulatorIndexRouteImport } from './routes/_simulator/index'
import { Route as SimulatorCodeRouteImport } from './routes/_simulator/$code'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as TvRemCodeRouteImport } from './routes/tv/rem.$code'
import { Route as TvRemoteIdRouteImport } from './routes/tv/remote.$id'
import { Route as TvApiClipsIdRouteImport } from './routes/tv/api/clips.$id'
import { Route as TvApiDisplaysIdEventsRouteImport } from './routes/tv/api/displays.$id.events'
import { Route as TvApiGroupsGroupIdDisplaysRouteImport } from './routes/tv/api/groups.$groupId.displays'
import { Route as TvApiGroupsGroupIdDisplaysIdRouteImport } from './routes/tv/api/groups.$groupId.displays.$id'
import { Route as TvApiGroupsGroupIdDisplaysIdReloadRouteImport } from './routes/tv/api/groups.$groupId.displays.$id.reload'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/_simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorIndexRoute = SimulatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulatorRoute,
} as any)
const SimulatorCodeRoute = SimulatorCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SimulatorRoute,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TvRoute,
} as any)
const TvRemCodeRoute = TvRemCodeRouteImport.update({
  id: '/rem/$code',
  path: '/rem/$code',
  getParentRoute: () => TvRoute,
} as any)
const TvRemoteIdRoute = TvRemoteIdRouteImport.update({
  id: '/remote/$id',
  path: '/remote/$id',
  getParentRoute: () => TvRoute,
} as any)
const TvApiClipsIdRoute = TvApiClipsIdRouteImport.update({
  id: '/api/clips/$id',
  path: '/api/clips/$id',
  getParentRoute: () => TvRoute,
} as any)
const TvApiDisplaysIdEventsRoute = TvApiDisplaysIdEventsRouteImport.update({
  id: '/api/displays/$id/events',
  path: '/api/displays/$id/events',
  getParentRoute: () => TvRoute,
} as any)
const TvApiGroupsGroupIdDisplaysRoute =
  TvApiGroupsGroupIdDisplaysRouteImport.update({
    id: '/api/groups/$groupId/displays',
    path: '/api/groups/$groupId/displays',
    getParentRoute: () => TvRoute,
  } as any)
const TvApiGroupsGroupIdDisplaysIdRoute =
  TvApiGroupsGroupIdDisplaysIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TvApiGroupsGroupIdDisplaysRoute,
  } as any)
const TvApiGroupsGroupIdDisplaysIdReloadRoute =
  TvApiGroupsGroupIdDisplaysIdReloadRouteImport.update({
    id: '/reload',
    path: '/reload',
    getParentRoute: () => TvApiGroupsGroupIdDisplaysIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SimulatorIndexRoute
  '/tv': typeof TvRouteWithChildren
  '/$code': typeof SimulatorCodeRoute
  '/tv/': typeof TvIndexRoute
  '/tv/rem/$code': typeof TvRemCodeRoute
  '/tv/remote/$id': typeof TvRemoteIdRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRoutesByTo {
  '/$code': typeof SimulatorCodeRoute
  '/': typeof SimulatorIndexRoute
  '/tv': typeof TvIndexRoute
  '/tv/rem/$code': typeof TvRemCodeRoute
  '/tv/remote/$id': typeof TvRemoteIdRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_simulator': typeof SimulatorRouteWithChildren
  '/tv': typeof TvRouteWithChildren
  '/_simulator/$code': typeof SimulatorCodeRoute
  '/_simulator/': typeof SimulatorIndexRoute
  '/tv/': typeof TvIndexRoute
  '/tv/rem/$code': typeof TvRemCodeRoute
  '/tv/remote/$id': typeof TvRemoteIdRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tv'
    | '/$code'
    | '/tv/'
    | '/tv/rem/$code'
    | '/tv/remote/$id'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$code'
    | '/'
    | '/tv'
    | '/tv/rem/$code'
    | '/tv/remote/$id'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  id:
    | '__root__'
    | '/_simulator'
    | '/tv'
    | '/_simulator/$code'
    | '/_simulator/'
    | '/tv/'
    | '/tv/rem/$code'
    | '/tv/remote/$id'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SimulatorRoute: typeof SimulatorRouteWithChildren
  TvRoute: typeof TvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_simulator': {
      id: '/_simulator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_simulator/': {
      id: '/_simulator/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SimulatorIndexRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/_simulator/$code': {
      id: '/_simulator/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof SimulatorCodeRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/tv/': {
      id: '/tv/'
      path: '/'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/rem/$code': {
      id: '/tv/rem/$code'
      path: '/rem/$code'
      fullPath: '/tv/rem/$code'
      preLoaderRoute: typeof TvRemCodeRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/remote/$id': {
      id: '/tv/remote/$id'
      path: '/remote/$id'
      fullPath: '/tv/remote/$id'
      preLoaderRoute: typeof TvRemoteIdRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/clips/$id': {
      id: '/tv/api/clips/$id'
      path: '/api/clips/$id'
      fullPath: '/tv/api/clips/$id'
      preLoaderRoute: typeof TvApiClipsIdRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/displays/$id/events': {
      id: '/tv/api/displays/$id/events'
      path: '/api/displays/$id/events'
      fullPath: '/tv/api/displays/$id/events'
      preLoaderRoute: typeof TvApiDisplaysIdEventsRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/groups/$groupId/displays': {
      id: '/tv/api/groups/$groupId/displays'
      path: '/api/groups/$groupId/displays'
      fullPath: '/tv/api/groups/$groupId/displays'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/groups/$groupId/displays/$id': {
      id: '/tv/api/groups/$groupId/displays/$id'
      path: '/$id'
      fullPath: '/tv/api/groups/$groupId/displays/$id'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysIdRouteImport
      parentRoute: typeof TvApiGroupsGroupIdDisplaysRoute
    }
    '/tv/api/groups/$groupId/displays/$id/reload': {
      id: '/tv/api/groups/$groupId/displays/$id/reload'
      path: '/reload'
      fullPath: '/tv/api/groups/$groupId/displays/$id/reload'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysIdReloadRouteImport
      parentRoute: typeof TvApiGroupsGroupIdDisplaysIdRoute
    }
  }
}

interface SimulatorRouteChildren {
  SimulatorCodeRoute: typeof SimulatorCodeRoute
  SimulatorIndexRoute: typeof SimulatorIndexRoute
}

const SimulatorRouteChildren: SimulatorRouteChildren = {
  SimulatorCodeRoute: SimulatorCodeRoute,
  SimulatorIndexRoute: SimulatorIndexRoute,
}

const SimulatorRouteWithChildren = SimulatorRoute._addFileChildren(
  SimulatorRouteChildren,
)

interface TvApiGroupsGroupIdDisplaysIdRouteChildren {
  TvApiGroupsGroupIdDisplaysIdReloadRoute: typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}

const TvApiGroupsGroupIdDisplaysIdRouteChildren: TvApiGroupsGroupIdDisplaysIdRouteChildren =
  {
    TvApiGroupsGroupIdDisplaysIdReloadRoute:
      TvApiGroupsGroupIdDisplaysIdReloadRoute,
  }

const TvApiGroupsGroupIdDisplaysIdRouteWithChildren =
  TvApiGroupsGroupIdDisplaysIdRoute._addFileChildren(
    TvApiGroupsGroupIdDisplaysIdRouteChildren,
  )

interface TvApiGroupsGroupIdDisplaysRouteChildren {
  TvApiGroupsGroupIdDisplaysIdRoute: typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
}

const TvApiGroupsGroupIdDisplaysRouteChildren: TvApiGroupsGroupIdDisplaysRouteChildren =
  {
    TvApiGroupsGroupIdDisplaysIdRoute:
      TvApiGroupsGroupIdDisplaysIdRouteWithChildren,
  }

const TvApiGroupsGroupIdDisplaysRouteWithChildren =
  TvApiGroupsGroupIdDisplaysRoute._addFileChildren(
    TvApiGroupsGroupIdDisplaysRouteChildren,
  )

interface TvRouteChildren {
  TvIndexRoute: typeof TvIndexRoute
  TvRemCodeRoute: typeof TvRemCodeRoute
  TvRemoteIdRoute: typeof TvRemoteIdRoute
  TvApiClipsIdRoute: typeof TvApiClipsIdRoute
  TvApiDisplaysIdEventsRoute: typeof TvApiDisplaysIdEventsRoute
  TvApiGroupsGroupIdDisplaysRoute: typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
}

const TvRouteChildren: TvRouteChildren = {
  TvIndexRoute: TvIndexRoute,
  TvRemCodeRoute: TvRemCodeRoute,
  TvRemoteIdRoute: TvRemoteIdRoute,
  TvApiClipsIdRoute: TvApiClipsIdRoute,
  TvApiDisplaysIdEventsRoute: TvApiDisplaysIdEventsRoute,
  TvApiGroupsGroupIdDisplaysRoute: TvApiGroupsGroupIdDisplaysRouteWithChildren,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SimulatorRoute: SimulatorRouteWithChildren,
  TvRoute: TvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
