/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/_simulator'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SimulatorIndexRouteImport } from './routes/_simulator/index'
import { Route as SimulatorCodeRouteImport } from './routes/_simulator/$code'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as TvCameraRouteImport } from './routes/tv/camera'
import { Route as TvApiReportsRouteImport } from './routes/tv/api/reports'
import { Route as TvApiClipsIdRouteImport } from './routes/tv/api/clips.$id'
import { Route as TvApiDisplaysIdEventsRouteImport } from './routes/tv/api/displays.$id.events'
import { Route as TvApiGroupsGroupIdCamerasRouteImport } from './routes/tv/api/groups.$groupId.cameras'
import { Route as TvApiGroupsGroupIdDisplaysRouteImport } from './routes/tv/api/groups.$groupId.displays'
import { Route as TvApiCamerasIdRecordingsRecordingIdRouteImport } from './routes/tv/api/cameras.$id.recordings.$recordingId'
import { Route as TvApiGroupsGroupIdCamerasIdRouteImport } from './routes/tv/api/groups.$groupId.cameras.$id'
import { Route as TvApiGroupsGroupIdDisplaysIdRouteImport } from './routes/tv/api/groups.$groupId.displays.$id'
import { Route as TvApiGroupsGroupIdDisplaysIdReloadRouteImport } from './routes/tv/api/groups.$groupId.displays.$id.reload'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/_simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorIndexRoute = SimulatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulatorRoute,
} as any)
const SimulatorCodeRoute = SimulatorCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SimulatorRoute,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TvRoute,
} as any)
const TvCameraRoute = TvCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => TvRoute,
} as any)
const TvApiReportsRoute = TvApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => TvRoute,
} as any)
const TvApiClipsIdRoute = TvApiClipsIdRouteImport.update({
  id: '/api/clips/$id',
  path: '/api/clips/$id',
  getParentRoute: () => TvRoute,
} as any)
const TvApiDisplaysIdEventsRoute = TvApiDisplaysIdEventsRouteImport.update({
  id: '/api/displays/$id/events',
  path: '/api/displays/$id/events',
  getParentRoute: () => TvRoute,
} as any)
const TvApiGroupsGroupIdCamerasRoute =
  TvApiGroupsGroupIdCamerasRouteImport.update({
    id: '/api/groups/$groupId/cameras',
    path: '/api/groups/$groupId/cameras',
    getParentRoute: () => TvRoute,
  } as any)
const TvApiGroupsGroupIdDisplaysRoute =
  TvApiGroupsGroupIdDisplaysRouteImport.update({
    id: '/api/groups/$groupId/displays',
    path: '/api/groups/$groupId/displays',
    getParentRoute: () => TvRoute,
  } as any)
const TvApiCamerasIdRecordingsRecordingIdRoute =
  TvApiCamerasIdRecordingsRecordingIdRouteImport.update({
    id: '/api/cameras/$id/recordings/$recordingId',
    path: '/api/cameras/$id/recordings/$recordingId',
    getParentRoute: () => TvRoute,
  } as any)
const TvApiGroupsGroupIdCamerasIdRoute =
  TvApiGroupsGroupIdCamerasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TvApiGroupsGroupIdCamerasRoute,
  } as any)
const TvApiGroupsGroupIdDisplaysIdRoute =
  TvApiGroupsGroupIdDisplaysIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TvApiGroupsGroupIdDisplaysRoute,
  } as any)
const TvApiGroupsGroupIdDisplaysIdReloadRoute =
  TvApiGroupsGroupIdDisplaysIdReloadRouteImport.update({
    id: '/reload',
    path: '/reload',
    getParentRoute: () => TvApiGroupsGroupIdDisplaysIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SimulatorIndexRoute
  '/tv': typeof TvRouteWithChildren
  '/$code': typeof SimulatorCodeRoute
  '/tv/camera': typeof TvCameraRoute
  '/tv/': typeof TvIndexRoute
  '/tv/api/reports': typeof TvApiReportsRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/cameras': typeof TvApiGroupsGroupIdCamerasRouteWithChildren
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/cameras/$id/recordings/$recordingId': typeof TvApiCamerasIdRecordingsRecordingIdRoute
  '/tv/api/groups/$groupId/cameras/$id': typeof TvApiGroupsGroupIdCamerasIdRoute
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRoutesByTo {
  '/$code': typeof SimulatorCodeRoute
  '/tv/camera': typeof TvCameraRoute
  '/': typeof SimulatorIndexRoute
  '/tv': typeof TvIndexRoute
  '/tv/api/reports': typeof TvApiReportsRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/cameras': typeof TvApiGroupsGroupIdCamerasRouteWithChildren
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/cameras/$id/recordings/$recordingId': typeof TvApiCamerasIdRecordingsRecordingIdRoute
  '/tv/api/groups/$groupId/cameras/$id': typeof TvApiGroupsGroupIdCamerasIdRoute
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_simulator': typeof SimulatorRouteWithChildren
  '/tv': typeof TvRouteWithChildren
  '/_simulator/$code': typeof SimulatorCodeRoute
  '/tv/camera': typeof TvCameraRoute
  '/_simulator/': typeof SimulatorIndexRoute
  '/tv/': typeof TvIndexRoute
  '/tv/api/reports': typeof TvApiReportsRoute
  '/tv/api/clips/$id': typeof TvApiClipsIdRoute
  '/tv/api/displays/$id/events': typeof TvApiDisplaysIdEventsRoute
  '/tv/api/groups/$groupId/cameras': typeof TvApiGroupsGroupIdCamerasRouteWithChildren
  '/tv/api/groups/$groupId/displays': typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  '/tv/api/cameras/$id/recordings/$recordingId': typeof TvApiCamerasIdRecordingsRecordingIdRoute
  '/tv/api/groups/$groupId/cameras/$id': typeof TvApiGroupsGroupIdCamerasIdRoute
  '/tv/api/groups/$groupId/displays/$id': typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
  '/tv/api/groups/$groupId/displays/$id/reload': typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tv'
    | '/$code'
    | '/tv/camera'
    | '/tv/'
    | '/tv/api/reports'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/cameras'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/cameras/$id/recordings/$recordingId'
    | '/tv/api/groups/$groupId/cameras/$id'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$code'
    | '/tv/camera'
    | '/'
    | '/tv'
    | '/tv/api/reports'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/cameras'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/cameras/$id/recordings/$recordingId'
    | '/tv/api/groups/$groupId/cameras/$id'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  id:
    | '__root__'
    | '/_simulator'
    | '/tv'
    | '/_simulator/$code'
    | '/tv/camera'
    | '/_simulator/'
    | '/tv/'
    | '/tv/api/reports'
    | '/tv/api/clips/$id'
    | '/tv/api/displays/$id/events'
    | '/tv/api/groups/$groupId/cameras'
    | '/tv/api/groups/$groupId/displays'
    | '/tv/api/cameras/$id/recordings/$recordingId'
    | '/tv/api/groups/$groupId/cameras/$id'
    | '/tv/api/groups/$groupId/displays/$id'
    | '/tv/api/groups/$groupId/displays/$id/reload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SimulatorRoute: typeof SimulatorRouteWithChildren
  TvRoute: typeof TvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_simulator': {
      id: '/_simulator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_simulator/': {
      id: '/_simulator/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SimulatorIndexRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/_simulator/$code': {
      id: '/_simulator/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof SimulatorCodeRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/tv/': {
      id: '/tv/'
      path: '/'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/camera': {
      id: '/tv/camera'
      path: '/camera'
      fullPath: '/tv/camera'
      preLoaderRoute: typeof TvCameraRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/reports': {
      id: '/tv/api/reports'
      path: '/api/reports'
      fullPath: '/tv/api/reports'
      preLoaderRoute: typeof TvApiReportsRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/clips/$id': {
      id: '/tv/api/clips/$id'
      path: '/api/clips/$id'
      fullPath: '/tv/api/clips/$id'
      preLoaderRoute: typeof TvApiClipsIdRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/displays/$id/events': {
      id: '/tv/api/displays/$id/events'
      path: '/api/displays/$id/events'
      fullPath: '/tv/api/displays/$id/events'
      preLoaderRoute: typeof TvApiDisplaysIdEventsRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/groups/$groupId/cameras': {
      id: '/tv/api/groups/$groupId/cameras'
      path: '/api/groups/$groupId/cameras'
      fullPath: '/tv/api/groups/$groupId/cameras'
      preLoaderRoute: typeof TvApiGroupsGroupIdCamerasRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/groups/$groupId/displays': {
      id: '/tv/api/groups/$groupId/displays'
      path: '/api/groups/$groupId/displays'
      fullPath: '/tv/api/groups/$groupId/displays'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/cameras/$id/recordings/$recordingId': {
      id: '/tv/api/cameras/$id/recordings/$recordingId'
      path: '/api/cameras/$id/recordings/$recordingId'
      fullPath: '/tv/api/cameras/$id/recordings/$recordingId'
      preLoaderRoute: typeof TvApiCamerasIdRecordingsRecordingIdRouteImport
      parentRoute: typeof TvRoute
    }
    '/tv/api/groups/$groupId/cameras/$id': {
      id: '/tv/api/groups/$groupId/cameras/$id'
      path: '/$id'
      fullPath: '/tv/api/groups/$groupId/cameras/$id'
      preLoaderRoute: typeof TvApiGroupsGroupIdCamerasIdRouteImport
      parentRoute: typeof TvApiGroupsGroupIdCamerasRoute
    }
    '/tv/api/groups/$groupId/displays/$id': {
      id: '/tv/api/groups/$groupId/displays/$id'
      path: '/$id'
      fullPath: '/tv/api/groups/$groupId/displays/$id'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysIdRouteImport
      parentRoute: typeof TvApiGroupsGroupIdDisplaysRoute
    }
    '/tv/api/groups/$groupId/displays/$id/reload': {
      id: '/tv/api/groups/$groupId/displays/$id/reload'
      path: '/reload'
      fullPath: '/tv/api/groups/$groupId/displays/$id/reload'
      preLoaderRoute: typeof TvApiGroupsGroupIdDisplaysIdReloadRouteImport
      parentRoute: typeof TvApiGroupsGroupIdDisplaysIdRoute
    }
  }
}

interface SimulatorRouteChildren {
  SimulatorCodeRoute: typeof SimulatorCodeRoute
  SimulatorIndexRoute: typeof SimulatorIndexRoute
}

const SimulatorRouteChildren: SimulatorRouteChildren = {
  SimulatorCodeRoute: SimulatorCodeRoute,
  SimulatorIndexRoute: SimulatorIndexRoute,
}

const SimulatorRouteWithChildren = SimulatorRoute._addFileChildren(
  SimulatorRouteChildren,
)

interface TvApiGroupsGroupIdCamerasRouteChildren {
  TvApiGroupsGroupIdCamerasIdRoute: typeof TvApiGroupsGroupIdCamerasIdRoute
}

const TvApiGroupsGroupIdCamerasRouteChildren: TvApiGroupsGroupIdCamerasRouteChildren =
  {
    TvApiGroupsGroupIdCamerasIdRoute: TvApiGroupsGroupIdCamerasIdRoute,
  }

const TvApiGroupsGroupIdCamerasRouteWithChildren =
  TvApiGroupsGroupIdCamerasRoute._addFileChildren(
    TvApiGroupsGroupIdCamerasRouteChildren,
  )

interface TvApiGroupsGroupIdDisplaysIdRouteChildren {
  TvApiGroupsGroupIdDisplaysIdReloadRoute: typeof TvApiGroupsGroupIdDisplaysIdReloadRoute
}

const TvApiGroupsGroupIdDisplaysIdRouteChildren: TvApiGroupsGroupIdDisplaysIdRouteChildren =
  {
    TvApiGroupsGroupIdDisplaysIdReloadRoute:
      TvApiGroupsGroupIdDisplaysIdReloadRoute,
  }

const TvApiGroupsGroupIdDisplaysIdRouteWithChildren =
  TvApiGroupsGroupIdDisplaysIdRoute._addFileChildren(
    TvApiGroupsGroupIdDisplaysIdRouteChildren,
  )

interface TvApiGroupsGroupIdDisplaysRouteChildren {
  TvApiGroupsGroupIdDisplaysIdRoute: typeof TvApiGroupsGroupIdDisplaysIdRouteWithChildren
}

const TvApiGroupsGroupIdDisplaysRouteChildren: TvApiGroupsGroupIdDisplaysRouteChildren =
  {
    TvApiGroupsGroupIdDisplaysIdRoute:
      TvApiGroupsGroupIdDisplaysIdRouteWithChildren,
  }

const TvApiGroupsGroupIdDisplaysRouteWithChildren =
  TvApiGroupsGroupIdDisplaysRoute._addFileChildren(
    TvApiGroupsGroupIdDisplaysRouteChildren,
  )

interface TvRouteChildren {
  TvCameraRoute: typeof TvCameraRoute
  TvIndexRoute: typeof TvIndexRoute
  TvApiReportsRoute: typeof TvApiReportsRoute
  TvApiClipsIdRoute: typeof TvApiClipsIdRoute
  TvApiDisplaysIdEventsRoute: typeof TvApiDisplaysIdEventsRoute
  TvApiGroupsGroupIdCamerasRoute: typeof TvApiGroupsGroupIdCamerasRouteWithChildren
  TvApiGroupsGroupIdDisplaysRoute: typeof TvApiGroupsGroupIdDisplaysRouteWithChildren
  TvApiCamerasIdRecordingsRecordingIdRoute: typeof TvApiCamerasIdRecordingsRecordingIdRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvCameraRoute: TvCameraRoute,
  TvIndexRoute: TvIndexRoute,
  TvApiReportsRoute: TvApiReportsRoute,
  TvApiClipsIdRoute: TvApiClipsIdRoute,
  TvApiDisplaysIdEventsRoute: TvApiDisplaysIdEventsRoute,
  TvApiGroupsGroupIdCamerasRoute: TvApiGroupsGroupIdCamerasRouteWithChildren,
  TvApiGroupsGroupIdDisplaysRoute: TvApiGroupsGroupIdDisplaysRouteWithChildren,
  TvApiCamerasIdRecordingsRecordingIdRoute:
    TvApiCamerasIdRecordingsRecordingIdRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SimulatorRoute: SimulatorRouteWithChildren,
  TvRoute: TvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
