import dayjs from "dayjs";

export const mockMatches = [
  {
    date: dayjs().subtract(0, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(0, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(0, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(1, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(2, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(2, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(2, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(4, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(4, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(7, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(7, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(7, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(7, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
  {
    date: dayjs().subtract(7, "days").toDate(),
    blueTeam: [{ name: "Bolls" }, { name: "Institut" }, { name: "Jonas" }],
    redTeam: [{ name: "Laurin" }, { name: "Ole" }, { name: "Robert" }],
    blueCups: 10,
    redCups: 2,
  },
];
