export const mockPlayers = [
    {
        name: 'Moritz',
        points: 278,
        matches: 40,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Schicke',
        points: 167,
        matches: 25,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Ole',
        points: 394,
        matches: 60,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Laurin',
        points: 356,
        matches: 56,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Institut',
        points: 140,
        matches: 23,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Timon',
        points: 313,
        matches: 52,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Bolls',
        points: 216,
        matches: 38,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Joel',
        points: 97,
        matches: 18,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Robert',
        points: 158,
        matches: 30,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Josi',
        points: 166,
        matches: 33,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Thies',
        points: 243,
        matches: 50,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Adriana',
        points: 71,
        matches: 17,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Elina',
        points: 232,
        matches: 69,
        matchesWon: 12,
        elo: 200,
    },
    {
        name: 'Jonas',
        points: 9,
        matches: 2,
        matchesWon: 2,
        elo: 200,
    },
].map((i, idx) => ({ ...i, id: idx.toString() }));
