spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 30
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
server:
  max-http-request-header-size: 64KB
sentry:
  #dsn: https://9118bf204e5738ecdfdc11a83507d8d3@o4508333440892928.ingest.de.sentry.io/4509607635058768
  dsn: ${SENTRY_DSN}
  debug: false
