services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build:
      context: ../api
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: jdbc:postgresql://database:5432/${POSTGRES_DB_NAME}
    networks:
      - backend
volumes:
  postgres:
networks:
  backend: