services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build:
      context: ../api
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      API_BASE_URL: ${API_BASE_URL}
      # Sentry
      BACKEND_SENTRY_DSN: ${BACKEND_SENTRY_DSN}
      # AWS
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - backend
volumes:
  postgres:
networks:
  backend:
