// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: formations.sql

package db

import (
	"context"
	"time"
)

const deleteFormation = `-- name: DeleteFormation :execrows
DELETE FROM formations WHERE id = $1 AND group_id = $2
`

type DeleteFormationParams struct {
	ID      string
	GroupID string
}

func (q *Queries) DeleteFormation(ctx context.Context, arg DeleteFormationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFormation, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const formationsByGroup = `-- name: FormationsByGroup :many
SELECT id, group_id, name, cups, created_by, created_at, updated_at FROM formations
WHERE group_id = $1
ORDER BY created_at, id
`

func (q *Queries) FormationsByGroup(ctx context.Context, groupID string) ([]Formation, error) {
	rows, err := q.db.Query(ctx, formationsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Formation
	for rows.Next() {
		var i Formation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Cups,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFormation = `-- name: UpsertFormation :one
INSERT INTO formations (id, group_id, name, cups, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT (id) DO UPDATE SET name = excluded.name, cups = excluded.cups, updated_at = excluded.updated_at
WHERE formations.group_id = excluded.group_id
RETURNING id, group_id, name, cups, created_by, created_at, updated_at
`

type UpsertFormationParams struct {
	ID        string
	GroupID   string
	Name      string
	Cups      string
	CreatedBy string
	CreatedAt time.Time
}

// A formation's id comes from the app, so a retried create is an update. A
// formation never moves to another group: then no row is returned.
func (q *Queries) UpsertFormation(ctx context.Context, arg UpsertFormationParams) (Formation, error) {
	row := q.db.QueryRow(ctx, upsertFormation,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Cups,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Formation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Cups,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
