// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"
)

const finishGroupCreation = `-- name: FinishGroupCreation :one
UPDATE groups SET active_season_id = $2, created_by = $3 WHERE id = $1
RETURNING id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by
`

type FinishGroupCreationParams struct {
	ID             string
	ActiveSeasonID *string
	CreatedBy      *string
}

func (q *Queries) FinishGroupCreation(ctx context.Context, arg FinishGroupCreationParams) (Group, error) {
	row := q.db.QueryRow(ctx, finishGroupCreation, arg.ID, arg.ActiveSeasonID, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by FROM groups WHERE invite_code = $1 LIMIT 1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode *string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const groupExists = `-- name: GroupExists :one
SELECT EXISTS (SELECT 1 FROM groups WHERE id = $1)
`

func (q *Queries) GroupExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, groupExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupWithStats = `-- name: GroupWithStats :one
SELECT
    g.id, g.created_at, g.custom_sport_name, g.invite_code, g.name, g.sport_preset, g.active_season_id, g.asset_id_wallpaper, g.created_by,
    (SELECT count(*) FROM matches m WHERE m.season_id = g.active_season_id) AS matches,
    (SELECT count(*) FROM players p WHERE p.season_id = g.active_season_id) AS players,
    (SELECT count(*) FROM seasons s WHERE s.group_id = g.id) AS seasons
FROM groups g
WHERE g.id = $1
`

type GroupWithStatsRow struct {
	Group   Group
	Matches int64
	Players int64
	Seasons int64
}

func (q *Queries) GroupWithStats(ctx context.Context, id string) (GroupWithStatsRow, error) {
	row := q.db.QueryRow(ctx, groupWithStats, id)
	var i GroupWithStatsRow
	err := row.Scan(
		&i.Group.ID,
		&i.Group.CreatedAt,
		&i.Group.CustomSportName,
		&i.Group.InviteCode,
		&i.Group.Name,
		&i.Group.SportPreset,
		&i.Group.ActiveSeasonID,
		&i.Group.AssetIDWallpaper,
		&i.Group.CreatedBy,
		&i.Matches,
		&i.Players,
		&i.Seasons,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by)
VALUES ($1, $2, $3, $4, $5, $6, NULL, NULL, NULL)
`

type InsertGroupParams struct {
	ID              string
	CreatedAt       *time.Time
	CustomSportName *string
	InviteCode      *string
	Name            *string
	SportPreset     *string
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.CreatedAt,
		arg.CustomSportName,
		arg.InviteCode,
		arg.Name,
		arg.SportPreset,
	)
	return err
}

const setGroupActiveSeason = `-- name: SetGroupActiveSeason :exec
UPDATE groups SET active_season_id = $2 WHERE id = $1
`

type SetGroupActiveSeasonParams struct {
	ID             string
	ActiveSeasonID *string
}

func (q *Queries) SetGroupActiveSeason(ctx context.Context, arg SetGroupActiveSeasonParams) error {
	_, err := q.db.Exec(ctx, setGroupActiveSeason, arg.ID, arg.ActiveSeasonID)
	return err
}

const setGroupWallpaper = `-- name: SetGroupWallpaper :one
UPDATE groups SET asset_id_wallpaper = $2 WHERE id = $1
RETURNING id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by
`

type SetGroupWallpaperParams struct {
	ID               string
	AssetIDWallpaper *string
}

func (q *Queries) SetGroupWallpaper(ctx context.Context, arg SetGroupWallpaperParams) (Group, error) {
	row := q.db.QueryRow(ctx, setGroupWallpaper, arg.ID, arg.AssetIDWallpaper)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups SET name = $2 WHERE id = $1
RETURNING id, created_at, custom_sport_name, invite_code, name, sport_preset, active_season_id, asset_id_wallpaper, created_by
`

type UpdateGroupNameParams struct {
	ID   string
	Name *string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CustomSportName,
		&i.InviteCode,
		&i.Name,
		&i.SportPreset,
		&i.ActiveSeasonID,
		&i.AssetIDWallpaper,
		&i.CreatedBy,
	)
	return i, err
}

const userGroupsWithStats = `-- name: UserGroupsWithStats :many
SELECT
    g.id, g.created_at, g.custom_sport_name, g.invite_code, g.name, g.sport_preset, g.active_season_id, g.asset_id_wallpaper, g.created_by,
    (SELECT count(*) FROM matches m WHERE m.season_id = g.active_season_id) AS matches,
    (SELECT count(*) FROM players p WHERE p.season_id = g.active_season_id) AS players,
    (SELECT count(*) FROM seasons s WHERE s.group_id = g.id) AS seasons
FROM groups g
WHERE g.id IN (SELECT gm.group_id FROM group_members gm WHERE gm.user_id = $1 AND gm.active)
ORDER BY g.ctid
`

type UserGroupsWithStatsRow struct {
	Group   Group
	Matches int64
	Players int64
	Seasons int64
}

// Groups the user hasn't left (leaving deactivates the membership), with
// counters for the active season.
func (q *Queries) UserGroupsWithStats(ctx context.Context, userID *string) ([]UserGroupsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, userGroupsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroupsWithStatsRow
	for rows.Next() {
		var i UserGroupsWithStatsRow
		if err := rows.Scan(
			&i.Group.ID,
			&i.Group.CreatedAt,
			&i.Group.CustomSportName,
			&i.Group.InviteCode,
			&i.Group.Name,
			&i.Group.SportPreset,
			&i.Group.ActiveSeasonID,
			&i.Group.AssetIDWallpaper,
			&i.Group.CreatedBy,
			&i.Matches,
			&i.Players,
			&i.Seasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
