// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID      string
	Offsetx float64
	Offsety float64
	Type    *int16
	Zoom    float64
}

type Device struct {
	ID                    string
	DeviceID              *string
	PushNotificationToken *string
	Type                  *int16
	UserID                *string
}

type Group struct {
	ID               string
	CreatedAt        *time.Time
	CustomSportName  *string
	InviteCode       *string
	Name             *string
	SportPreset      *string
	ActiveSeasonID   *string
	AssetIDWallpaper *string
	CreatedBy        *string
}

type GroupMember struct {
	ID      string
	Active  bool
	GroupID *string
	UserID  *string
}

type Match struct {
	ID        string
	Date      *time.Time
	SeasonID  *string
	CreatedBy *string
}

type MatchMove struct {
	ID           string
	Value        int32
	MoveID       *string
	TeamMemberID *string
}

type Player struct {
	ID               string
	ActiveThisSeason bool
	ProfileID        *string
	SeasonID         *string
	StatisticsID     *string
}

type Profile struct {
	ID            string
	Name          *string
	AssetIDAvatar *string
	GroupID       *string
	CreatedBy     *string
}

type Rule struct {
	ID          string
	Description *string
	Title       *string
	SeasonID    *string
	CreatedBy   *string
}

type RuleMove struct {
	ID              string
	FinishingMove   bool
	Name            *string
	PointsForScorer int32
	PointsForTeam   int32
	SeasonID        *string
}

type Season struct {
	ID               string
	EndDate          *time.Time
	GroupID          *string
	Name             *string
	StartDate        *time.Time
	SeasonSettingsID *string
	CreatedBy        *string
}

type SeasonSetting struct {
	ID                  string
	DailyLeaderboard    *int16
	MaxTeamSize         int32
	MinMatchesToQualify int32
	MinTeamSize         int32
	RankingAlgorithm    *int16
	WakeTime            pgtype.Time
}

type Statistic struct {
	ID                string
	AvgPointsPerMatch float64
	AvgTeamSize       float64
	Elo               float64
	Matches           int64
	Moves             int64
	Points            int64
	TotalTeamSize     int64
	Wins              *int64
}

type Team struct {
	ID           string
	MatchID      *string
	AssetIDPhoto *string
}

type TeamMember struct {
	ID       string
	PlayerID *string
	TeamID   *string
}

type User struct {
	ID string
}
