// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, asset_id_avatar, group_id, created_by FROM profiles WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssetIDAvatar,
		&i.GroupID,
		&i.CreatedBy,
	)
	return i, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO profiles (id, name, asset_id_avatar, group_id, created_by)
VALUES ($1, $2, NULL, $3, $4)
RETURNING id, name, asset_id_avatar, group_id, created_by
`

type InsertProfileParams struct {
	ID        string
	Name      *string
	GroupID   *string
	CreatedBy *string
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, insertProfile,
		arg.ID,
		arg.Name,
		arg.GroupID,
		arg.CreatedBy,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssetIDAvatar,
		&i.GroupID,
		&i.CreatedBy,
	)
	return i, err
}

type InsertProfilesParams struct {
	ID        string
	Name      *string
	GroupID   *string
	CreatedBy *string
}

const profileByGroupAndName = `-- name: ProfileByGroupAndName :one
SELECT id, name, asset_id_avatar, group_id, created_by FROM profiles WHERE group_id = $1 AND name IS NOT DISTINCT FROM $2::text
LIMIT 1
`

type ProfileByGroupAndNameParams struct {
	GroupID *string
	Name    *string
}

// A missing name matches profiles without a name, like Spring Data's
// derived query did.
func (q *Queries) ProfileByGroupAndName(ctx context.Context, arg ProfileByGroupAndNameParams) (Profile, error) {
	row := q.db.QueryRow(ctx, profileByGroupAndName, arg.GroupID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssetIDAvatar,
		&i.GroupID,
		&i.CreatedBy,
	)
	return i, err
}

const profileExistsInGroup = `-- name: ProfileExistsInGroup :one
SELECT EXISTS (SELECT 1 FROM profiles WHERE id = $1 AND group_id = $2)
`

type ProfileExistsInGroupParams struct {
	ID      string
	GroupID *string
}

func (q *Queries) ProfileExistsInGroup(ctx context.Context, arg ProfileExistsInGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, profileExistsInGroup, arg.ID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const profilesByGroup = `-- name: ProfilesByGroup :many
SELECT id, name, asset_id_avatar, group_id, created_by FROM profiles WHERE group_id = $1 ORDER BY ctid
`

func (q *Queries) ProfilesByGroup(ctx context.Context, groupID *string) ([]Profile, error) {
	rows, err := q.db.Query(ctx, profilesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AssetIDAvatar,
			&i.GroupID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProfileAvatar = `-- name: SetProfileAvatar :one
UPDATE profiles SET asset_id_avatar = $2 WHERE id = $1
RETURNING id, name, asset_id_avatar, group_id, created_by
`

type SetProfileAvatarParams struct {
	ID            string
	AssetIDAvatar *string
}

func (q *Queries) SetProfileAvatar(ctx context.Context, arg SetProfileAvatarParams) (Profile, error) {
	row := q.db.QueryRow(ctx, setProfileAvatar, arg.ID, arg.AssetIDAvatar)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssetIDAvatar,
		&i.GroupID,
		&i.CreatedBy,
	)
	return i, err
}

const updateProfileName = `-- name: UpdateProfileName :one
UPDATE profiles SET name = $2 WHERE id = $1
RETURNING id, name, asset_id_avatar, group_id, created_by
`

type UpdateProfileNameParams struct {
	ID   string
	Name *string
}

func (q *Queries) UpdateProfileName(ctx context.Context, arg UpdateProfileNameParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileName, arg.ID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssetIDAvatar,
		&i.GroupID,
		&i.CreatedBy,
	)
	return i, err
}
