// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"
	"time"
)

const activeSeasonIDOfGroup = `-- name: ActiveSeasonIDOfGroup :one
SELECT id FROM seasons WHERE group_id = $1 AND end_date IS NULL LIMIT 1
`

func (q *Queries) ActiveSeasonIDOfGroup(ctx context.Context, groupID *string) (string, error) {
	row := q.db.QueryRow(ctx, activeSeasonIDOfGroup, groupID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const endSeason = `-- name: EndSeason :exec
UPDATE seasons SET name = $2, end_date = $3 WHERE id = $1
`

type EndSeasonParams struct {
	ID      string
	Name    *string
	EndDate *time.Time
}

func (q *Queries) EndSeason(ctx context.Context, arg EndSeasonParams) error {
	_, err := q.db.Exec(ctx, endSeason, arg.ID, arg.Name, arg.EndDate)
	return err
}

const getSeason = `-- name: GetSeason :one

SELECT
    s.id, s.name, s.start_date, s.end_date, s.group_id, s.created_by, s.season_settings_id,
    ss.min_matches_to_qualify, ss.min_team_size, ss.max_team_size,
    ss.ranking_algorithm, ss.daily_leaderboard,
    -- Java's DTO renders a missing wake time as its default "00:00"
    COALESCE(to_char(ss.wake_time, 'HH24:MI:SS'), '00:00')::text AS wake_time
FROM seasons s
LEFT JOIN season_settings ss ON ss.id = s.season_settings_id
WHERE s.id = $1
`

type GetSeasonRow struct {
	ID                  string
	Name                *string
	StartDate           *time.Time
	EndDate             *time.Time
	GroupID             *string
	CreatedBy           *string
	SeasonSettingsID    *string
	MinMatchesToQualify *int32
	MinTeamSize         *int32
	MaxTeamSize         *int32
	RankingAlgorithm    *int16
	DailyLeaderboard    *int16
	WakeTime            string
}

// Seasons are always read together with their settings. A season without
// settings is legal in the schema, hence the LEFT JOIN.
func (q *Queries) GetSeason(ctx context.Context, id string) (GetSeasonRow, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i GetSeasonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.GroupID,
		&i.CreatedBy,
		&i.SeasonSettingsID,
		&i.MinMatchesToQualify,
		&i.MinTeamSize,
		&i.MaxTeamSize,
		&i.RankingAlgorithm,
		&i.DailyLeaderboard,
		&i.WakeTime,
	)
	return i, err
}

const insertSeason = `-- name: InsertSeason :exec
INSERT INTO seasons (id, end_date, group_id, name, start_date, season_settings_id, created_by)
VALUES ($1, NULL, $2, NULL, $3, $4, $5)
`

type InsertSeasonParams struct {
	ID               string
	GroupID          *string
	StartDate        *time.Time
	SeasonSettingsID *string
	CreatedBy        *string
}

func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) error {
	_, err := q.db.Exec(ctx, insertSeason,
		arg.ID,
		arg.GroupID,
		arg.StartDate,
		arg.SeasonSettingsID,
		arg.CreatedBy,
	)
	return err
}

const insertSeasonSettings = `-- name: InsertSeasonSettings :exec
INSERT INTO season_settings (id, daily_leaderboard, max_team_size, min_matches_to_qualify, min_team_size, ranking_algorithm, wake_time)
VALUES ($1, $2, $3, $4, $5, $6, $7::text::time)
`

type InsertSeasonSettingsParams struct {
	ID                  string
	DailyLeaderboard    *int16
	MaxTeamSize         int32
	MinMatchesToQualify int32
	MinTeamSize         int32
	RankingAlgorithm    *int16
	WakeTime            *string
}

func (q *Queries) InsertSeasonSettings(ctx context.Context, arg InsertSeasonSettingsParams) error {
	_, err := q.db.Exec(ctx, insertSeasonSettings,
		arg.ID,
		arg.DailyLeaderboard,
		arg.MaxTeamSize,
		arg.MinMatchesToQualify,
		arg.MinTeamSize,
		arg.RankingAlgorithm,
		arg.WakeTime,
	)
	return err
}

const seasonExists = `-- name: SeasonExists :one
SELECT EXISTS (SELECT 1 FROM seasons WHERE id = $1)
`

func (q *Queries) SeasonExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, seasonExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seasonExistsInGroup = `-- name: SeasonExistsInGroup :one
SELECT EXISTS (SELECT 1 FROM seasons WHERE id = $1 AND group_id = $2)
`

type SeasonExistsInGroupParams struct {
	ID      string
	GroupID *string
}

func (q *Queries) SeasonExistsInGroup(ctx context.Context, arg SeasonExistsInGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, seasonExistsInGroup, arg.ID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seasonsByGroup = `-- name: SeasonsByGroup :many
SELECT
    s.id, s.name, s.start_date, s.end_date, s.group_id, s.created_by, s.season_settings_id,
    ss.min_matches_to_qualify, ss.min_team_size, ss.max_team_size,
    ss.ranking_algorithm, ss.daily_leaderboard,
    -- Java's DTO renders a missing wake time as its default "00:00"
    COALESCE(to_char(ss.wake_time, 'HH24:MI:SS'), '00:00')::text AS wake_time
FROM seasons s
LEFT JOIN season_settings ss ON ss.id = s.season_settings_id
WHERE s.group_id = $1
ORDER BY s.ctid
`

type SeasonsByGroupRow struct {
	ID                  string
	Name                *string
	StartDate           *time.Time
	EndDate             *time.Time
	GroupID             *string
	CreatedBy           *string
	SeasonSettingsID    *string
	MinMatchesToQualify *int32
	MinTeamSize         *int32
	MaxTeamSize         *int32
	RankingAlgorithm    *int16
	DailyLeaderboard    *int16
	WakeTime            string
}

func (q *Queries) SeasonsByGroup(ctx context.Context, groupID *string) ([]SeasonsByGroupRow, error) {
	rows, err := q.db.Query(ctx, seasonsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonsByGroupRow
	for rows.Next() {
		var i SeasonsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.GroupID,
			&i.CreatedBy,
			&i.SeasonSettingsID,
			&i.MinMatchesToQualify,
			&i.MinTeamSize,
			&i.MaxTeamSize,
			&i.RankingAlgorithm,
			&i.DailyLeaderboard,
			&i.WakeTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonSettings = `-- name: UpdateSeasonSettings :exec
UPDATE season_settings SET
    daily_leaderboard = $2,
    max_team_size = $3,
    min_matches_to_qualify = $4,
    min_team_size = $5,
    ranking_algorithm = $6,
    wake_time = $7::text::time
WHERE id = $1
`

type UpdateSeasonSettingsParams struct {
	ID                  string
	DailyLeaderboard    *int16
	MaxTeamSize         int32
	MinMatchesToQualify int32
	MinTeamSize         int32
	RankingAlgorithm    *int16
	WakeTime            *string
}

func (q *Queries) UpdateSeasonSettings(ctx context.Context, arg UpdateSeasonSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSeasonSettings,
		arg.ID,
		arg.DailyLeaderboard,
		arg.MaxTeamSize,
		arg.MinMatchesToQualify,
		arg.MinTeamSize,
		arg.RankingAlgorithm,
		arg.WakeTime,
	)
	return err
}
