/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemoteIdRouteImport } from './routes/remote.$id'
import { Route as ApiDisplaysIdEventsRouteImport } from './routes/api/displays.$id.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIdRoute = RemoteIdRouteImport.update({
  id: '/remote/$id',
  path: '/remote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplaysIdEventsRoute = ApiDisplaysIdEventsRouteImport.update({
  id: '/api/displays/$id/events',
  path: '/api/displays/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/remote/$id': typeof RemoteIdRoute
  '/api/displays/$id/events': typeof ApiDisplaysIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/remote/$id': typeof RemoteIdRoute
  '/api/displays/$id/events': typeof ApiDisplaysIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/remote/$id': typeof RemoteIdRoute
  '/api/displays/$id/events': typeof ApiDisplaysIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/remote/$id' | '/api/displays/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/remote/$id' | '/api/displays/$id/events'
  id: '__root__' | '/' | '/remote/$id' | '/api/displays/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RemoteIdRoute: typeof RemoteIdRoute
  ApiDisplaysIdEventsRoute: typeof ApiDisplaysIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$id': {
      id: '/remote/$id'
      path: '/remote/$id'
      fullPath: '/remote/$id'
      preLoaderRoute: typeof RemoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/displays/$id/events': {
      id: '/api/displays/$id/events'
      path: '/api/displays/$id/events'
      fullPath: '/api/displays/$id/events'
      preLoaderRoute: typeof ApiDisplaysIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RemoteIdRoute: RemoteIdRoute,
  ApiDisplaysIdEventsRoute: ApiDisplaysIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
