import { SeasonCardProps } from '@/components/screens/PastSeasonsEmptyScreen';

export const mockSeasons: SeasonCardProps[] = [
    {
        minMatchesRequiredToBeRanked: 0,
        season: {
            name: 'Vacation Kroatia',
            startDate: '',
            endDate: '',
            numMatches: 0,
            numPlayers: 0,
        },
        players: [
            {
                id: '#0',
                name: 'Moritz',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#1',
                name: 'Timon',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#2',
                name: 'Bolls',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#3',
                name: 'Ole',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#4',
                name: 'Thies',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
        ],
        numMatches: 0,
    },
    {
        minMatchesRequiredToBeRanked: 0,
        season: {
            name: 'Winter Semester',
            startDate: '',
            endDate: '',
        },
        players: [
            {
                id: '#0',
                name: 'Moritz',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#1',
                name: 'Timon',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#2',
                name: 'Bolls',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#3',
                name: 'Ole',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#4',
                name: 'Thies',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
        ],
        numMatches: 0,
    },
    {
        minMatchesRequiredToBeRanked: 0,
        season: {
            name: 'Vacation Bochum',
            startDate: '',
            endDate: '',
        },
        players: [
            {
                id: '#0',
                name: 'Moritz',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#1',
                name: 'Timon',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#2',
                name: 'Bolls',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#3',
                name: 'Ole',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
            {
                id: '#4',
                name: 'Thies',
                points: 120,
                matches: 10,
                matchesWon: 10,
                elo: 1500,
                profileId: '',
                cups: 0,
            },
        ],
        numMatches: 0,
    },
];
