spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 30
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
server:
  max-http-request-header-size: 64KB
sentry:
  dsn: ${BACKEND_SENTRY_DSN}
  debug: false
app:
  aws:
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET_NAME}
    endpoint: ${AWS_ENDPOINT}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}