name: Bump mobile app version and submit

on:
  workflow_dispatch:
    inputs:
      patch_update:
        description: 'Enter "true" for staging "false" for prod'
        required: true
        type: boolean
        default: true

jobs:
  bump-version:
    name: Bump version of package.json and app.json
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump version
        id: bump_version
        run: |
          cd mobile-app
          
          # Read current version from package.json
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"
          
          # Increment patch version
          if [[ "${{ inputs.patch_update }}" == "true" ]]; then
            new_version=$(node -e "
              const [major, minor, patch] = '$current_version'.split('.');
              console.log(\`\${major}.\${minor}.\${parseInt(patch) + 1}\`);
            ")
          else
            new_version=$(node -e "
              const [major, minor, patch] = '$current_version'.split('.');
              console.log(\`\${major}.\${parseInt(minor) + 1}.\${patch}\`);
            ")
          fi
          echo "New version: $new_version"
          
          # Update package.json
          jq --arg version "$new_version" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
          
          # Update app.json
          jq --arg version "$new_version" '.expo.version = $version' app.json > app.json.tmp && mv app.json.tmp app.json
          
          echo "Updated version in package.json and app.json to $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT


      - run: npm ci && npm run format
        working-directory: mobile-app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Bump app version to ${{ steps.bump_version.outputs.new_version }}
          title: Bump app version to ${{ steps.bump_version.outputs.new_version }} and submit
          branch: bump-app-version-${{ steps.bump_version.outputs.new_version }}
          base: ${{ github.head_ref }}
          delete-branch: true
          token: ${{ secrets.PAT }}
