name: Generate OpenApi

# please refer to OPENAPI_CODEGEN.md for details on this workflow

on:
  push:
    paths:
      - "api-go/openapi/openapi.json"
  pull_request:
    paths:
      - "api-go/openapi/openapi.json"
  workflow_dispatch:

jobs:
  generate-types:
    permissions:
      contents: write
    name: Generate client types
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "mobile-app/package-lock.json"

      - name: Generate client types
        working-directory: mobile-app
        run: |
          npm ci
          npm run gen-types
          npx prettier --write api/generated/openapi.json openapi/openapi.d.ts

      - name: Commit generated types
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update openapi types"
          file_pattern: "mobile-app/api/generated/openapi.json mobile-app/openapi/openapi.d.ts"
