name: Generate OpenApi

on: 
  pull_request:
    paths:
      - "api/src/main/java/pro/beerpong/api/**"
      - ".github/workflows/generate-openapi.yaml"
    branches: 
      - main
  workflow_dispatch:

jobs:
  generate-docs: 
    name: Genereate Api docs
    runs-on: ubuntu-20.04
    container: node:20-bookworm-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_DB: beerpong
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21 corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: mvn verify
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_URL: jdbc:postgresql://postgres:5432/beerpong
        working-directory: api
