name: Generate OpenApi

on: 
  pull_request:
    paths:
      - "api/src/main/**"
      - ".github/workflows/generate-openapi.yaml"
      - "mobile-app/api/generated/openapi.json"
      - "mobile-app/openapi/openapi.d.ts"
    branches: 
      - main
  workflow_dispatch:

jobs:
  generate-docs: 
    permissions:
      contents: write
      pull-requests: write
    name: Genereate Api docs
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_DB: beerpong
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

            
      - name: Check latest commit author
        id: check_author
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
          if echo "$COMMIT_AUTHOR" | grep -q "github-actions"; then
            echo "has_bot_author=true" >> $GITHUB_OUTPUT
            echo "Latest commit was authored by a GitHub bot. Stopping the workflow."
            exit 78  # This will stop the workflow without failing it
          else
            echo "has_bot_author=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK 21 corretto
        if: steps.check_author.outputs.has_bot_author != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Cache Maven packages
        if: steps.check_author.outputs.has_bot_author != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - run: mvn verify
        if: steps.check_author.outputs.has_bot_author != 'true'
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_URL: jdbc:postgresql://localhost:5432/beerpong
        working-directory: api
      - run: sed -i 's#"\*/\*"#"application/json"#g' ./mobile-app/api/generated/openapi.json
        if: steps.check_author.outputs.has_bot_author != 'true'

      - name: Cache npm packages
        if: steps.check_author.outputs.has_bot_author != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        if: steps.check_author.outputs.has_bot_author != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'mobile-app/package-lock.json'

      - run: npm ci && npm run gen-types && npm run format
        if: steps.check_author.outputs.has_bot_author != 'true'
        working-directory: mobile-app

      - name: Create Pull Request
        if: steps.check_author.outputs.has_bot_author != 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: chore - update openapi-types
          title: OpenAPI Types Update
          branch: update-openapi-types
          base: ${{ github.head_ref }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
