name: Generate OpenApi

on: 
  push:
    paths:
      - "api/src/main/java/pro/beerpong/api/**"
      - ".github/workflows/generate-openapi.yaml"
      - "mobile-app/api/generated/openapi.json"
      - "mobile-app/openapi/openapi.d.ts"
    branches: 
      - main
  workflow_dispatch:

jobs:
  generate-docs: 
    permissions:
      contents: write
      pull-requests: write
    name: Genereate Api docs
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_DB: beerpong
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21 corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: mvn verify
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: user
          POSTGRES_URL: jdbc:postgresql://localhost:5432/beerpong
        working-directory: api
      - run: sed -i 's#"\*/\*"#"application/json"#g' ./mobile-app/api/generated/openapi.json
      - run: npm i && npm run gen-types && npm run format
        working-directory: mobile-app
      - run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: chore - update openapi-types
          title: OpenAPI Types Update
          base: main
          branch: update-openapi-types
